
// -------------------------------------------------------------------------------------------
//      Editor
// -------------------------------------------------------------------------------------------

// Modes
#DEFINE MGUI_EDITOR_MODE_SELECT         0
#DEFINE MGUI_EDITOR_MODE_MOVE           1
#DEFINE MGUI_EDITOR_MODE_SCALE          2
#DEFINE MGUI_EDITOR_MODE_WRAP           3
#DEFINE MGUI_EDITOR_MODE_ALPHA          4


bool    mguiEditorIsRunning;
int     mguiEditorMode;

// Brush state
str     mguiEditorBrushContent,
        mguiEditorBrushFont;
int     mguiEditorBrushType, 
        mguiEditorBrushXFactor,
        mguiEditorBrushYFactor,
        mguiEditorBrushWrap,
        mguiEditorBrushAlpha;
bool    mguiEditorIsUniformScale;

script "MegaUI Editor" (void) CLIENTSIDE {
    if(!StartMouseMenu("MegaUI Editor Event"))
        terminate;
    mguiEditorIsRunning = true;
    mguiEditorIsUniformScale = true;
    mguiEditorBrushFont = "SMALLFONT";
    SetPlayerProperty(0, 1, PROP_TOTALLYFROZEN);
    MGUIEditor_SetMode(MGUI_EDITOR_MODE_SELECT);
    int x, y, hudWidth, hudHeight;

    // Main thread
    while(true) {

        MGUIEditor_CheckInput();

        // Brush modes
        if(     (mguiEditorMode==MGUI_EDITOR_MODE_MOVE) 
            |   (mguiEditorMode==MGUI_EDITOR_MODE_SCALE) 
            |   (mguiEditorMode==MGUI_EDITOR_MODE_WRAP)) {

            
            // Draw the brush
            hudWidth = MGUIEditor_ToHud(mguiEditorBrushXFactor, MGUI_HUD_WIDTH), 
            hudHeight = MGUIEditor_ToHud(mguiEditorBrushYFactor, MGUI_HUD_HEIGHT),
            x = (GetMouseX()*hudWidth)>>16,
            y = (GetMouseY()*hudHeight)>>16;

            switch(mguiEditorBrushType) {
                case MGUI_EDITOR_BRUSH_TEXT:
                    DrawText(mguiEditorBrushContent, mguiEditorBrushFont, x, y, hudWidth, hudHeight, 
                        MGUIEditor_ToHud(mguiEditorBrushWrap, hudWidth), mguiEditorBrushAlpha);
                    break;
                case MGUI_EDITOR_BRUSH_GRAPHIC:
                    Draw(mguiEditorBrushContent, x, y, hudWidth, hudHeight, mguiEditorBrushAlpha);
                    break;
            }
        }
        delay(1);
    }
    SetPlayerProperty(0, 0, PROP_TOTALLYFROZEN);
    mguiEditorIsRunning = false;
    EndMouseMenu();
}

function void MGUIEditor_SetMode(int mode) {
    mguiEditorMode = mode;
    switch(mode) {
        case MGUI_EDITOR_MODE_SELECT:
            SetMouseCursor("MEGAUI_3"); SetMouseOffset(6, 8); SetMouseSpeed(1.0); break;

        case MGUI_EDITOR_MODE_MOVE:
            SetMouseCursor("MEGAUI_4"); SetMouseOffset(0, 0); SetMouseSpeed(1.0); break;

        case MGUI_EDITOR_MODE_SCALE:
            SetMouseCursor("MEGAUI_5"); SetMouseOffset(0, 0); SetMouseSpeed(0.0); break;

        case MGUI_EDITOR_MODE_WRAP:
            SetMouseCursor("MEGAUI_7"); SetMouseOffset(0, 0); SetMouseSpeed(0.0); break;
    }
}

function void MGUIEditor_ToBrush(int type, str content, int xFactor, int yFactor, str font, int wrap, int alpha) {
    MGUIEditor_Play(MGUI_EDITOR_SFX_BRUSH);
    MGUIEditor_SetMode(MGUI_EDITOR_MODE_MOVE);
    mguiEditorBrushType = type;
    mguiEditorBrushContent = content;
    mguiEditorBrushXFactor = xFactor;
    mguiEditorBrushYFactor = yFactor;
    mguiEditorBrushFont = font;
    mguiEditorBrushWrap = (type==MGUI_EDITOR_BRUSH_GRAPHIC ? 0 : wrap);
    mguiEditorBrushAlpha = alpha;
}
