
#DEFINE MGUI_EDITOR_MOUSE_DELTA     0.002
#DEFINE MGUI_EDITOR_SCALE_DELTA     0.003125
#DEFINE MGUI_EDITOR_WRAP_DELTA      0.003125
#DEFINE MGUI_EDITOR_ALPHA_DELTA     0.01
#DEFINE MGUI_EDITOR_HOLD_DURACTION  10

// Catch left/right click events (Mouse menu callback script)
script "MegaUI Editor Event" (int e, int areaId) CLIENTSIDE {
    switch(e) {

        // Mouse enters area
        case MGUI_EVENT_ENTER:
            MGUIEditor_DrawStampHook(areaId, true);
            break;

        // Mouse exits area
        case MGUI_EVENT_EXIT:
            MGUIEditor_DrawStampHook(areaId, false);
            break;

        // Left click press
        case MGUI_EVENT_DOWN:
            switch(mguiEditorMode) {

                case MGUI_EDITOR_MODE_SELECT:
                    if(areaId != MGUI_AREA_NULL) {
                        int slot = MGUIEditor_GetSlotFromStampId(areaId);
                        MGUIEditor_ToBrush(MGUIEditor_GetStampType(slot),
                            mguiEditorStampContent[slot],
                            mguiEditorStampXFactor[slot],
                            mguiEditorStampYFactor[slot],
                            mguiEditorStampFont[slot],
                            mguiEditorStampWrap[slot],
                            mguiEditorStampAlpha[slot]);
                        MGUIEditor_DeleteStamp(areaId);
                    }
                    break;

                case MGUI_EDITOR_MODE_MOVE:
                    MGUIEditor_SetStamp(mguiEditorStampCount, mguiEditorBrushContent, GetMouseX(), GetMouseY(), 
                        mguiEditorBrushXFactor, mguiEditorBrushYFactor, mguiEditorBrushFont, mguiEditorBrushWrap, mguiEditorBrushAlpha);
                    mguiEditorStampCount++;
                    MGUIEditor_Play(MGUI_EDITOR_SFX_STAMP_ADD);
                    MGUIEditor_SetMode(MGUI_EDITOR_MODE_SELECT);
                    break;
            }
            break;

        // Right click press
        case MGUI_EVENT_ALT_DOWN:
            switch(mguiEditorMode) {

                case MGUI_EDITOR_MODE_SELECT: 
                    if(areaId != MGUI_AREA_NULL) {
                        MGUIEditor_Play(MGUI_EDITOR_SFX_STAMP_REMOVE);
                        MGUIEditor_DeleteStamp(areaId);
                    }
                    break;

                case MGUI_EDITOR_MODE_MOVE:
                    MGUIEditor_SetMode(MGUI_EDITOR_MODE_SCALE);
                    break;
            }
            break;

        // Right click release
        case MGUI_EVENT_ALT_UP:
            if(mguiEditorMode==MGUI_EDITOR_MODE_SCALE)
                MGUIEditor_SetMode(MGUI_EDITOR_MODE_MOVE);
            break;

    }
}

#DEFINE MGUI_EDITOR_CHAT_MODE_IDLE  0
#DEFINE MGUI_EDITOR_CHAT_MODE_FONT  1
int mguiEditor_ChatMode = MGUI_EDITOR_CHAT_MODE_IDLE;

script "MegaUI Editor Chat" (int type, int message, int arg2) EVENT {
    if(!mguiEditorIsRunning)
        terminate;
    if (type == GAMEEVENT_CHAT) {
        message = GetChatMessage(message, 0);
        switch(mguiEditor_ChatMode) {

            case MGUI_EDITOR_CHAT_MODE_IDLE:
                if(mguiEditorStampCount == MGUI_EDITOR_STAMP_MAX) {
                    MGUIEditor_Play(MGUI_EDITOR_SFX_NO);
                    MGUIEditor_Log(strParam(s:"Error : stamp limit of ", d:MGUI_EDITOR_STAMP_MAX, s:" reached!!"));
                }
                else 
                    MGUIEditor_ToBrush(mguiEditorBrushType, message, mguiEditorBrushXFactor, mguiEditorBrushYFactor, 
                        mguiEditorBrushFont, mguiEditorBrushWrap, 1.0);
                break;

            case MGUI_EDITOR_CHAT_MODE_FONT:
                if(!CheckFont(message))
                    MGUIEditor_ShowBanner(strParam(s:"Warning : font ", s:message, s:" does not exist!"));
                else
                    mguiEditorBrushFont = message;
                mguiEditor_ChatMode = MGUI_EDITOR_CHAT_MODE_IDLE;
                break;
        }
    }
}

#DEFINE MGUI_EDITOR_KEY_HOLD_DURATION   12
#DEFINE MGUI_EDITOR_KEY_UP              0
#DEFINE MGUI_EDITOR_KEY_DOWN            1
#DEFINE MGUI_EDITOR_KEY_LEFT            2
#DEFINE MGUI_EDITOR_KEY_RIGHT           3
#DEFINE MGUI_EDITOR_KEY_RELOAD          4
int mguiEditorKeyState[5];

function bool MGUIEditor_IsKeyHeld(int key) { return mguiEditorKeyState[key] >= MGUI_EDITOR_HOLD_DURACTION; }

// Catch buttons press events (except from left/right click)
function void MGUIEditor_CheckInput(void) {
    int input = GetPlayerInput(-1, INPUT_BUTTONS);
    int prevInput = GetPlayerInput(-1, INPUT_OLDBUTTONS);
    int pressedInput = (input ^ prevInput) & ~prevInput;

    if(MGUIEditor_InBrushMode()) {

        // Font change
        if(MGUIEditor_IsKeyHeld(MGUI_EDITOR_KEY_RELOAD)) {
            if(mguiEditor_ChatMode != MGUI_EDITOR_CHAT_MODE_FONT) {
                MGUIEditor_Play(MGUI_EDITOR_SFX_RESET);
                MGUIEditor_ShowBanner("Type the font name in chat");
                mguiEditor_ChatMode = MGUI_EDITOR_CHAT_MODE_FONT;
            }
        }
        else if(pressedInput & BT_RELOAD)
            mguiEditor_ChatMode = MGUI_EDITOR_CHAT_MODE_IDLE;
        // Toggle text/graphic brush type
        else if(!(input & BT_RELOAD) && (prevInput & BT_RELOAD)) {
            int tmp = mguiEditorBrushType==MGUI_EDITOR_BRUSH_TEXT; 
            MGUIEditor_ToBrush(tmp ? MGUI_EDITOR_BRUSH_GRAPHIC : MGUI_EDITOR_BRUSH_TEXT,
                mguiEditorBrushContent, mguiEditorBrushXFactor, mguiEditorBrushYFactor, 
                mguiEditorBrushFont, tmp ? 0 : 1.0, mguiEditorBrushAlpha);
        }

        // Text wrap mode on/off
        if(mguiEditorBrushType==MGUI_EDITOR_BRUSH_TEXT) {
            if((input & BT_CROUCH) ^ (prevInput & BT_CROUCH))
                MGUIEditor_SetMode(input & BT_CROUCH ? MGUI_EDITOR_MODE_WRAP : MGUI_EDITOR_MODE_MOVE);
        }

        // Alpha mode on/off
        if((input & BT_JUMP) ^ (prevInput & BT_JUMP))
            MGUIEditor_SetMode(input & BT_JUMP ? MGUI_EDITOR_MODE_ALPHA : MGUI_EDITOR_MODE_MOVE);

        // Toggle uniform scale
        if(pressedInput & BT_SHOWSCORES) {
            MGUIEditor_Play(MGUI_EDITOR_SFX_TOGGLE);
            mguiEditorIsUniformScale = !mguiEditorIsUniformScale;
            MGUIEditor_ShowBanner(strParam(s:"Keep scale aspect ratio ", s:mguiEditorIsUniformScale ? MGUI_EDITOR_TEXT_ON : MGUI_EDITOR_TEXT_OFF));
        }


        int w = (pressedInput & BT_FORWARD)     | MGUIEditor_IsKeyHeld(MGUI_EDITOR_KEY_UP),
            s = (pressedInput & BT_BACK)        | MGUIEditor_IsKeyHeld(MGUI_EDITOR_KEY_DOWN),
            a = (pressedInput & BT_MOVELEFT)    | MGUIEditor_IsKeyHeld(MGUI_EDITOR_KEY_LEFT),
            d = (pressedInput & BT_MOVERIGHT)   | MGUIEditor_IsKeyHeld(MGUI_EDITOR_KEY_RIGHT);
        // Mouse delta / WASD calc
        switch(mguiEditorMode) {
            case MGUI_EDITOR_MODE_MOVE:
                tmp = FixedDiv(MGUI_EDITOR_MOUSE_DELTA, mguiEditorBrushXFactor);
                if(a)           SetMouseX(GetMouseX()-tmp);
                else if(d)      SetMouseX(GetMouseX()+tmp);
                tmp = FixedDiv(MGUI_EDITOR_MOUSE_DELTA, mguiEditorBrushYFactor);
                if(w)           SetMouseY(GetMouseY()-tmp);
                else if(s)      SetMouseY(GetMouseY()+tmp);
                break;
            
            case MGUI_EDITOR_MODE_SCALE:
                // Mouse
                int mouseX = GetRawMouseDeltaX()<<4;
                int mouseY = GetRawMouseDeltaY()<<4;

                // >>> Up/left
                if((mouseX > 0) | (mouseY > 0)) {
                    if(mguiEditorIsUniformScale) {
                        tmp = MGUI_Max(mouseX, mouseY);
                        mguiEditorBrushXFactor = FixedMul(mguiEditorBrushXFactor, 1.0 + tmp);
                        mguiEditorBrushYFactor = FixedMul(mguiEditorBrushYFactor, 1.0 + tmp);
                    }
                    else {
                        if(mouseX > 0)  mguiEditorBrushXFactor = FixedMul(mguiEditorBrushXFactor, 1.0 + mouseX);
                        if(mouseY > 0)  mguiEditorBrushYFactor = FixedMul(mguiEditorBrushYFactor, 1.0 + mouseY);
                    }
                }

                // >>> Down/right
                else if((mouseX < 0) | (mouseY < 0)) {
                    if(mguiEditorIsUniformScale) {
                        tmp = MGUI_Min(mouseX, mouseY);
                        mguiEditorBrushXFactor = FixedDiv(mguiEditorBrushXFactor, 1.0 - tmp);
                        mguiEditorBrushYFactor = FixedDiv(mguiEditorBrushYFactor, 1.0 - tmp);
                    }
                    else {
                        if(mouseX < 0)  mguiEditorBrushXFactor = FixedDiv(mguiEditorBrushXFactor, 1.0 - mouseX);
                        if(mouseY < 0)  mguiEditorBrushYFactor = FixedDiv(mguiEditorBrushYFactor, 1.0 - mouseY);
                    }
                }

                // Keyboard
                mouseX = 1.0+FixedDiv(MGUI_EDITOR_SCALE_DELTA, mguiEditorBrushXFactor),
                mouseY = 1.0+FixedDiv(MGUI_EDITOR_SCALE_DELTA, mguiEditorBrushYFactor);
                if(a | w) {
                    if(a | mguiEditorIsUniformScale)
                        mguiEditorBrushXFactor = FixedMul(mguiEditorBrushXFactor, mouseX);
                    if(w | mguiEditorIsUniformScale)         
                        mguiEditorBrushYFactor = FixedMul(mguiEditorBrushYFactor, mouseY);
                }
                else if(d | s) {
                    if(d | mguiEditorIsUniformScale)         
                        mguiEditorBrushXFactor = FixedDiv(mguiEditorBrushXFactor, mouseX);
                    if(s | mguiEditorIsUniformScale)         
                        mguiEditorBrushYFactor = FixedDiv(mguiEditorBrushYFactor, mouseY);
                }
                break;
            
            case MGUI_EDITOR_MODE_WRAP:
                tmp = GetRawMouseDeltaX()<<2;
                if(tmp)         mguiEditorBrushWrap = MGUI_Clamp(mguiEditorBrushWrap-tmp, 0.01, 1.0);
                tmp = FixedDiv(MGUI_EDITOR_WRAP_DELTA, mguiEditorBrushXFactor);
                if(a)           mguiEditorBrushWrap = MGUI_Max(mguiEditorBrushWrap-tmp, 0.01);
                else if(d)      mguiEditorBrushWrap = MGUI_Min(mguiEditorBrushWrap+tmp, 1.0);
                break;
            
            case MGUI_EDITOR_MODE_ALPHA:
                tmp = GetRawMouseDeltaX()<<1;
                if(tmp)         mguiEditorBrushAlpha = MGUI_Clamp(mguiEditorBrushAlpha-tmp, 0.01, 1.0);
                if(a)           mguiEditorBrushAlpha = MGUI_Max(mguiEditorBrushAlpha-MGUI_EDITOR_ALPHA_DELTA, 0.00);
                else if(d)      mguiEditorBrushAlpha = MGUI_Min(mguiEditorBrushAlpha+MGUI_EDITOR_ALPHA_DELTA, 1.0);
                break;
        }
    }


    // Update 
    mguiEditorKeyState[MGUI_EDITOR_KEY_UP] = (input & BT_FORWARD) ? mguiEditorKeyState[MGUI_EDITOR_KEY_UP]+1 : 0;
    mguiEditorKeyState[MGUI_EDITOR_KEY_DOWN] = (input & BT_BACK) ? mguiEditorKeyState[MGUI_EDITOR_KEY_DOWN]+1 : 0;
    mguiEditorKeyState[MGUI_EDITOR_KEY_LEFT] = (input & BT_MOVELEFT) ? mguiEditorKeyState[MGUI_EDITOR_KEY_LEFT]+1 : 0;
    mguiEditorKeyState[MGUI_EDITOR_KEY_RIGHT] = (input & BT_MOVERIGHT) ? mguiEditorKeyState[MGUI_EDITOR_KEY_RIGHT]+1 : 0;
    mguiEditorKeyState[MGUI_EDITOR_KEY_RELOAD] = (input & BT_RELOAD) ? mguiEditorKeyState[MGUI_EDITOR_KEY_RELOAD]+1 : 0;
}


function void MGUIEditor_ScaleModeCalc(int input) {
}
