
#DEFINE MGUI_EDITOR_MOUSE_DELTA     0.002
#DEFINE MGUI_EDITOR_SCALE_DELTA     1.03
#DEFINE MGUI_EDITOR_WRAP_DELTA      0.006
#DEFINE MGUI_EDITOR_HOLD_DURACTION  15

int MGUIEditor_ReloadInput;

// Catch left/right click events (Mouse menu callback script)
script "MegaUI Editor Event" (int e, int areaId) CLIENTSIDE {
    switch(e) {

        // Mouse enters area
        case MGUI_EVENT_ENTER:
            MGUIEditor_DrawStampHook(areaId, true);
            break;

        // Mouse exits area
        case MGUI_EVENT_EXIT:
            MGUIEditor_DrawStampHook(areaId, false);
            break;

        // Left click press
        case MGUI_EVENT_DOWN:
            switch(mguiEditorMode) {

                case MGUI_EDITOR_MODE_SELECT:
                    if(areaId != MGUI_AREA_NULL) {
                        int slot = MGUIEditor_GetSlotFromStampId(areaId);
                        MGUIEditor_ToBrush(MGUIEditor_GetStampType(slot),
                            mguiEditorStampContent[slot],
                            mguiEditorStampXFactor[slot],
                            mguiEditorStampYFactor[slot],
                            mguiEditorStampFont[slot],
                            mguiEditorStampWrap[slot],
                            mguiEditorStampAlpha[slot]);
                        MGUIEditor_DeleteStamp(areaId);
                    }
                    break;

                case MGUI_EDITOR_MODE_MOVE:
                    MGUIEditor_SetStamp(mguiEditorStampCount, mguiEditorBrushContent, GetMouseX(), GetMouseY(), 
                        mguiEditorBrushXFactor, mguiEditorBrushYFactor, mguiEditorBrushFont, mguiEditorBrushWrap, mguiEditorBrushAlpha);
                    mguiEditorStampCount++;
                    MGUIEditor_Play(MGUI_EDITOR_SFX_STAMP_ADD);
                    MGUIEditor_SetMode(MGUI_EDITOR_MODE_SELECT);
                    break;
            }
            break;

        // Right click press
        case MGUI_EVENT_ALT_DOWN:
            switch(mguiEditorMode) {

                case MGUI_EDITOR_MODE_SELECT: 
                    if(areaId != MGUI_AREA_NULL) {
                        MGUIEditor_Play(MGUI_EDITOR_SFX_STAMP_REMOVE);
                        MGUIEditor_DeleteStamp(areaId);
                    }
                    break;

                case MGUI_EDITOR_MODE_MOVE:
                    MGUIEditor_SetMode(MGUI_EDITOR_MODE_SCALE);
                    break;
            }
            break;

        // Right click release
        case MGUI_EVENT_ALT_UP:
            if(mguiEditorMode==MGUI_EDITOR_MODE_SCALE)
                MGUIEditor_SetMode(MGUI_EDITOR_MODE_MOVE);
            break;

    }
}

script "MegaUI Editor Chat" (int type, int message, int arg2) EVENT {
    if(!mguiEditorIsRunning)
        terminate;
    if (type == GAMEEVENT_CHAT) {
        message = GetChatMessage(message, 0);
        if(MGUIEditor_ReloadInput < MGUI_EDITOR_HOLD_DURACTION) {
            if(mguiEditorStampCount == MGUI_EDITOR_STAMP_MAX) {
                MGUIEditor_Play(MGUI_EDITOR_SFX_NO);
                MGUIEDitor_Log(strParam(s:"Error : stamp limit of ", d:MGUI_EDITOR_STAMP_MAX, s:" reached!!"));
            }
            else 
                MGUIEditor_ToBrush(mguiEditorBrushType, message, 1.0, 1.0, mguiEditorBrushFont, 1.0, 1.0);
        }
        else {
            MGUIEditor_ReloadInput = 0;
            mguiEditorBrushFont = message;
        }
    }
}

// Catch buttons press events (except from left/right click)
function void MGUIEditor_CheckInput(void) {
    int input = GetPlayerInput(-1, INPUT_BUTTONS);
    int prevInput = GetPlayerInput(-1, INPUT_OLDBUTTONS);
    int pressedInput = (input ^ prevInput) & ~prevInput;

    if((mguiEditorMode==MGUI_EDITOR_MODE_MOVE) | (mguiEditorMode==MGUI_EDITOR_MODE_SCALE) | (mguiEditorMode==MGUI_EDITOR_MODE_WRAP)) {

        if((input & BT_RELOAD) ^ (prevInput & BT_RELOAD)) {
            if(input & BT_RELOAD)
                MGUIEditor_ReloadInput = 0;

            // Toggle text/graphic brush type
            else if(MGUIEditor_ReloadInput < MGUI_EDITOR_HOLD_DURACTION) {
                int tmp = mguiEditorBrushType==MGUI_EDITOR_BRUSH_TEXT; 
                MGUIEditor_ToBrush(tmp ? MGUI_EDITOR_BRUSH_GRAPHIC : MGUI_EDITOR_BRUSH_TEXT,
                    mguiEditorBrushContent, mguiEditorBrushXFactor, mguiEditorBrushYFactor, 
                    mguiEditorBrushFont, tmp ? 0 : 1.0, mguiEditorBrushAlpha);
            }
        }
        // Font change
        else if(input & BT_RELOAD) {
            if(MGUIEditor_ReloadInput == MGUI_EDITOR_HOLD_DURACTION) {
                MGUIEditor_Play(MGUI_EDITOR_SFX_RESET);
                MGUIEditor_Log("Type the new font in chat!!");
            }
            MGUIEditor_ReloadInput++;
        }


        // Toggle text wrap mode
        if((mguiEditorMode != MGUI_EDITOR_MODE_SCALE) & (mguiEditorBrushType==MGUI_EDITOR_BRUSH_TEXT)) {
            if((input & BT_JUMP) ^ (prevInput & BT_JUMP))
                MGUIEditor_SetMode(input & BT_JUMP ? MGUI_EDITOR_MODE_WRAP : MGUI_EDITOR_MODE_MOVE);
        }

        // Toggle uniform scale
        if(pressedInput & BT_SHOWSCORES) {
            MGUIEditor_Play(MGUI_EDITOR_SFX_TOGGLE);
            mguiEditorIsUniformScale = !mguiEditorIsUniformScale;
            MGUIEditor_Log(strParam(s:"Uniform scale is now ", d:mguiEditorIsUniformScale));
        }
    }

    switch(mguiEditorMode) {
        case MGUI_EDITOR_MODE_MOVE:
            if(input & BT_MOVELEFT)       SetMouseX(GetMouseX()-MGUI_EDITOR_MOUSE_DELTA);
            else if(input & BT_MOVERIGHT) SetMouseX(GetMouseX()+MGUI_EDITOR_MOUSE_DELTA);
            if(input & BT_FORWARD)        SetMouseY(GetMouseY()-MGUI_EDITOR_MOUSE_DELTA);
            else if(input & BT_BACK)      SetMouseY(GetMouseY()+MGUI_EDITOR_MOUSE_DELTA);
            break;
        
        case MGUI_EDITOR_MODE_SCALE:
            MGUIEditor_ScaleModeCalc(input);
            break;
        
        case MGUI_EDITOR_MODE_WRAP:
            tmp = GetRawMouseDeltaX()<<2;
            if(tmp)                         mguiEditorBrushWrap = MGUI_Clamp(mguiEditorBrushWrap-tmp, 0.01, 1.0);
            if(input & BT_MOVELEFT)         mguiEditorBrushWrap = MGUI_Max(mguiEditorBrushWrap-MGUI_EDITOR_WRAP_DELTA, 0.01);
            else if(input & BT_MOVERIGHT)   mguiEditorBrushWrap = MGUI_Min(mguiEditorBrushWrap+MGUI_EDITOR_WRAP_DELTA, 1.0);
            break;
    }
}


function void MGUIEditor_ScaleModeCalc(int input) {
    // Mouse
    int mouseX = GetRawMouseDeltaX()<<4;
    int mouseY = GetRawMouseDeltaY()<<4;

    // >>> Up/left
    if((mouseX > 0) | (mouseY > 0)) {
        if(mguiEditorIsUniformScale) {
            int tmp = MGUI_Max(mouseX, mouseY);
            mguiEditorBrushXFactor = FixedMul(mguiEditorBrushXFactor, 1.0 + tmp);
            mguiEditorBrushYFactor = FixedMul(mguiEditorBrushYFactor, 1.0 + tmp);
        }
        else {
            if(mouseX > 0)  mguiEditorBrushXFactor = FixedMul(mguiEditorBrushXFactor, 1.0 + mouseX);
            if(mouseY > 0)  mguiEditorBrushYFactor = FixedMul(mguiEditorBrushYFactor, 1.0 + mouseY);
        }
    }

    // >>> Down/right
    else if((mouseX < 0) | (mouseY < 0)) {
        if(mguiEditorIsUniformScale) {
            tmp = MGUI_Min(mouseX, mouseY);
            mguiEditorBrushXFactor = FixedDiv(mguiEditorBrushXFactor, 1.0 - tmp);
            mguiEditorBrushYFactor = FixedDiv(mguiEditorBrushYFactor, 1.0 - tmp);
        }
        else {
            if(mouseX < 0)  mguiEditorBrushXFactor = FixedDiv(mguiEditorBrushXFactor, 1.0 - mouseX);
            if(mouseY < 0)  mguiEditorBrushYFactor = FixedDiv(mguiEditorBrushYFactor, 1.0 - mouseY);
        }
    }

    // Keyboard
    if(input & (BT_MOVELEFT|BT_FORWARD)) {
        if((input & BT_MOVELEFT) | mguiEditorIsUniformScale)
            mguiEditorBrushXFactor = FixedMul(mguiEditorBrushXFactor, MGUI_EDITOR_SCALE_DELTA);
        if((input & BT_FORWARD) | mguiEditorIsUniformScale)         
            mguiEditorBrushYFactor = FixedMul(mguiEditorBrushYFactor, MGUI_EDITOR_SCALE_DELTA);
    }
    else if(input & (BT_MOVERIGHT|BT_BACK)) {
        if((input & BT_MOVERIGHT)|mguiEditorIsUniformScale)         
            mguiEditorBrushXFactor = FixedDiv(mguiEditorBrushXFactor, MGUI_EDITOR_SCALE_DELTA);
        if((input & BT_BACK)|mguiEditorIsUniformScale)         
            mguiEditorBrushYFactor = FixedDiv(mguiEditorBrushYFactor, MGUI_EDITOR_SCALE_DELTA);
    }
}
