
                //////////////////////////////////////////////////////////////
                //                                                          //
                //   ███╗   ███╗███████╗ ██████╗  █████╗     ██╗   ██╗██╗   //
                //   ████╗ ████║██╔════╝██╔════╝ ██╔══██╗    ██║   ██║██║   //
                //   ██╔████╔██║█████╗  ██║  ███╗███████║    ██║   ██║██║   //
                //   ██║╚██╔╝██║██╔══╝  ██║   ██║██╔══██║    ██║   ██║██║   //
                //   ██║ ╚═╝ ██║███████╗╚██████╔╝██║  ██║    ╚██████╔╝██║   //
                //   ╚═╝     ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝   //
                //                                                          //
                //////////////////////////////////////////////////////////////
                //                   Last updated: 1.0.0                    //
                //////////////////////////////////////////////////////////////


// -------------------------------------------------------------------------------------------
//      General
// -------------------------------------------------------------------------------------------

/*
- To use MegaUI, copy this megaUI.acs file to your mod and use #include "megaUI.acs"
    - Optionally, copy MegaUI's graphics/debug content to your mod (for MGUI_SetDebug() below function to work)
- All functions are meant for CLIENTSIDE scripting (NamedExecuteClientScript)
- x and y are NON-fixed ints (i.e 160, 120 ; NOT 160.0, 120.0) for position
- hudWidth and hudHeight represents SetHudSize's "scaling" width/height parameters (i.e 320, 240)
*/

// Turn debug on/off. Debug displays MegaUI errors, mouse areas' hitbox, and a crosshair on mouse's position
function void MGUI_SetDebug(bool state) { ACS_NamedExecuteWithResult("MegaUI API", -1, state); }

// -------------------------------------------------------------------------------------------
//      API ~ Rendering
// -------------------------------------------------------------------------------------------

// ShowText/DrawText flags
#DEFINE MGUI_CENTER 0x80000000 // Center text (SetHudSize's x |= 0.4)
#DEFINE MGUI_TYPEON 0x40000000 // Delayed text typing (HUDMSG_TYPEON) => for example, 0.6s delay => `flags = MGUI_TYPEON | 0.6`

// Draws a graphic on screen
function void Show(int hudMessageId, str graphic, int x, int y, int hudWidth, int hudHeight, int alpha) {
    MGUI_DrawCore(hudMessageId, "A", graphic, x, y, hudWidth, hudHeight, alpha, 0); 
}

// Draws a graphic on screen for 1 tic only
function void Draw(str graphic, int x, int y, int hudWidth, int hudHeight, int alpha) { 
    Show(0, graphic, x, y, hudWidth, hudHeight, alpha); 
}

// Draws text on screen
function void ShowText(int hudMessageId, str text, str font, int x, int y, int hudWidth, int hudHeight, int wrap, int alpha, int flags) {
    MGUI_DrawTextCore(hudMessageId, text, font, x, y, hudWidth, hudHeight, wrap, alpha, flags);
}

// Draws text on screen for 1 tic only
function void DrawText(str text, str font, int x, int y, int hudWidth, int hudHeight, int wrap, int alpha, int flags) { 
    ShowText(0, text, font, x, y, hudWidth, hudHeight, wrap, alpha, flags);
}

// Erase a Show() or ShowText() rendered element from screen
function void Hide(int hudMessageId) { 
    HudMessageBold(s:""; HUDMSG_PLAIN, hudMessageId, 0, 0, 0, 0, 0); 
}

// Erase <count> consecutive rendered elements, starting from <hudMessageId>
function void HideRange(int hudMessageId, int count) {
    for(int i = 0; i < count; i++) 
        Hide(hudMessageId+i);
}

// Do not render pixels outside the given rectangle (SetHudClipRect)
// hudWith is same value as the incoming to-be-cropped element's hudWidth
function void Crop(int left, int top, int width, int height, int hudWidth) { 
    MGUI_CropCore(left, top, width, height, hudWidth);
}

// Stop previous Crop()'s effect
function void Uncrop(void) { 
    MGUI_UncropCore();
}


// -------------------------------------------------------------------------------------------
//      API ~ Mouse Menu
// -------------------------------------------------------------------------------------------

#DEFINE MGUI_NULL_AREA                  0x7FFFFFFF

// Mouse Menu events for callback script
#DEFINE MGUI_EVENT_ENTER                0 // On mouse enter area
#DEFINE MGUI_EVENT_EXIT                 1 // On mouse leave area
#DEFINE MGUI_EVENT_DOWN                 2 // On fire button press
#DEFINE MGUI_EVENT_UP                   3 // On fire button release
#DEFINE MGUI_EVENT_ALT_DOWN             4 // On altfire button press
#DEFINE MGUI_EVENT_ALT_UP               5 // On altfire button release

// Enables mouse menu. It will send mouse events to the given @scriptName callback script with the arguments (int e, int areaId) :
// @e event type
// @areaId the mouse area id that triggered it (or MGUI_NULL_AREA if none)
// ==> return false if could not start due to another mod already using mouse menu <==
function bool   StartMouseMenu(str scriptName) {    return ACS_NamedExecuteWithResult("MegaUI Mouse Menu", scriptName); }

// Stops mouse menu
function void   EndMouseMenu(void) {                ACS_NamedExecuteWithResult("MegaUI API", 0); }

/*  Registers an area that sends mouse events. Width/height is the area's dimensions, as if it was a graphic file
    > areaId must be >= 0
    > When the mouse is within several areas, only the one with lowest areaId will trigger events (similar to hudMessage id priority) */
function void   SetMouseArea(int areaId, int x, int y, int width, int height, int hudWidth, int hudHeight) { 
    ACS_NamedExecuteWithResult("MegaUI SetMouseArea API", areaId, (y<<16)|x, (height<<16)|width, (hudHeight<<16)|hudWidth); }

// Unregisters an area
function void   DeleteMouseArea(int areaId) {       ACS_NamedExecuteWithResult("MegaUI API", 1, areaId); }

// Change mouse speed multiplier (default 1.0)
function void   SetMouseSpeed(int speed) {          ACS_NamedExecuteWithResult("MegaUI API", 2, speed); }

// Customize mouse's graphic / pixel offset from origin / graphic scale (Hud Size)
function void   SetCustomMouse(str graphic, int offsetX, int offsetY, int hudWidth, int hudHeight) { ACS_NamedExecuteWithResult("MegaUI API", 3, graphic, (offsetY)<<16|offsetX, (hudHeight<<16)|hudWidth); }

// Mouse's normalized position :
//  > 0.0 for left (X) / top (Y) of the screen
//  > 1.0 for right (X) / bottom (Y) of the screen
function int    GetMouseX(void) {                   return ACS_NamedExecuteWithResult("MegaUI API", 4); }
function void   SetMouseX(int value) {              ACS_NamedExecuteWithResult("MegaUI API", 5, value); }
function int    GetMouseY(void) {                   return ACS_NamedExecuteWithResult("MegaUI API", 6); }
function void   SetMouseY(int value) {              ACS_NamedExecuteWithResult("MegaUI API", 7, value); }

// Get the physical mouse's position difference since previous tic (unitless)
function int    GetRawMouseDeltaX(void) {           return GetPlayerInput(-1, INPUT_YAW); }
function int    GetRawMouseDeltaY(void) {           return (GetPlayerInput(-1, INPUT_PITCH)*GetScreenWidth())/GetScreenHeight(); }


// -------------------------------------------------------------------------------------------
//      API ~ END
// -------------------------------------------------------------------------------------------



/*
// ---------------------------------------------------------------------------------------------------------------------------------------- //
// ---------------------------------------------------------------------------------------------------------------------------------------- //
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                            Internal       
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ---------------------------------------------------------------------------------------------------------------------------------------- //
// ---------------------------------------------------------------------------------------------------------------------------------------- //
*/

#DEFINE MGUI_HUD_WIDTH              320
#DEFINE MGUI_HUD_HEIGHT             240

#DEFINE MGUI_CROP_POS               -0x7FFF
#DEFINE MGUI_CROP_SIZE              0xFFFE

bool                                mguiIsDebug = false;

function void   MGUI_Log(str message) {             if(mguiIsDebug) log(s:"\c[v7][\c[x5] MegaUI \c[v7]] \c-",s:message); }
function int    MGUI_Min(int x, int y) {            return (x>y ? y : x); }
function int    MGUI_Max(int x, int y) {            return (x>y ? x : y); }
function int    MGUI_Clamp(int n, int l, int r) {   return MGUI_Max(MGUI_Min(n,r),l); }
function int    MGUI_Roundf(int n) {                return (n+0.5)&0xFFFF0000; }

// Adjust x position for widescreen / non-4:3 resolution
function int MGUI_ToVirtualX(int x, int hudWidth) {
    int rangeX = FixedDiv(FixedDiv(GetScreenWidth()<<16, GetScreenHeight()<<16),1.333333)*hudWidth;
    hudWidth<<=16;
    int x1 = (hudWidth - rangeX)>>1;
    return MGUI_Roundf(x1 + FixedMul(((hudWidth + rangeX)>>1)-x1, (FixedDiv(x<<16, hudWidth)))); // Lerp
}

    ///////////////
    // Rendering //
    ///////////////

int cropX = MGUI_CROP_POS,
    cropY = MGUI_CROP_POS,
    cropWidth = MGUI_CROP_SIZE,
    cropHeight = MGUI_CROP_SIZE;

function void MGUI_DrawCore(int hudMessageId, str value, str font, int x, int y, int hudWidth, int hudHeight, int alpha, int flags) {
	SetHudSize(hudWidth, hudHeight, true);
	SetFont(font); 
    if(flags & MGUI_TYPEON) {
        HudMessageBold(s:value; HUDMSG_PLAIN|HUDMSG_ALPHA|HUDMSG_TYPEON, hudMessageId, CR_UNTRANSLATED,
            MGUI_ToVirtualX(x, hudWidth) | (flags & MGUI_CENTER ? 0.4 : 0), y<<16, 0x8000000, (flags & 0x0FFFFFFF), 0x80000000, alpha);
    }
    else {
        HudMessageBold(s:value; HUDMSG_PLAIN|HUDMSG_ALPHA, hudMessageId, CR_UNTRANSLATED,
            MGUI_ToVirtualX(x, hudWidth) | (flags & MGUI_CENTER ? 0.4 : 0), y<<16, (hudMessageId ? 0x8000000 : 1873), alpha);
    }
}

function void MGUI_DrawTextCore(int hudMessageId, str text, str font, int x, int y, int hudWidth, int hudHeight, int wrap, int alpha, int flags) {
    if(wrap) SetHudClipRect(cropX, cropY, cropWidth, cropHeight, wrap);
    MGUI_DrawCore(hudMessageId, text, font, x, y, hudWidth, hudHeight, alpha, flags);
    if(wrap) SetHudClipRect(cropX, cropY, cropWidth, cropHeight);
}

function void MGUI_CropCore(int left, int top, int width, int height, int hudWidth) { 
    cropX = (MGUI_ToVirtualX(left+(width>>1), hudWidth)>>16)-(width>>1),
    cropY = top,
    cropWidth = width,
    cropHeight = height;
    SetHudClipRect(cropX, cropY, cropWidth, cropHeight, 0);
}

function void MGUI_UncropCore(void) {
    cropX = MGUI_CROP_POS, 
    cropY = MGUI_CROP_POS, 
    cropWidth = MGUI_CROP_SIZE, 
    cropHeight = MGUI_CROP_SIZE;
    SetHudClipRect(0, 0, 0, 0, 0); 
}

    /////////////////
    // Mouse menu  //
    /////////////////

#DEFINE MGUI_MOUSE_AREA_MAX         256
#DEFINE MGUI_DEBUG_AREA_DRAWID      1
#DEFINE MGUI_DEBUG_AREA_DRAWID_END  MGUI_DEBUG_AREA_DRAWID+MGUI_MOUSE_AREA_MAX

#DEFINE MGUI_MOUSE_INTERACT         BT_ATTACK
#DEFINE MGUI_MOUSE_ALT_INTERACT     BT_ALTATTACK

int mguiIsMouseMenuRunning =       false,
    mguiMouseGraphic =          "DOOMCURS",
    mguiMouseOffsetX =          7,
    mguiMouseOffsetY =          14,
    mguiMouseX =                0.5,
    mguiMouseY =                0.5,
    mguiMouseHudWidth =         MGUI_HUD_WIDTH,
    mguiMouseHudHeight =        MGUI_HUD_HEIGHT,
    mguiMouseSpeed =            1.0,
    mguiMouseScript =           "MegaUI Mouse Callback ???";

int     mguiMouseAreaCount = 0;

int     mguiMouseAreaIds[MGUI_MOUSE_AREA_MAX+1],
        mguiMouseAreaX1[MGUI_MOUSE_AREA_MAX+1],
        mguiMouseAreaX2[MGUI_MOUSE_AREA_MAX+1],
        mguiMouseAreaY1[MGUI_MOUSE_AREA_MAX+1],
        mguiMouseAreaY2[MGUI_MOUSE_AREA_MAX+1]; 

int     mguiMouseAreaDebugPos[MGUI_MOUSE_AREA_MAX+1],
        mguiMouseAreaDebugSize[MGUI_MOUSE_AREA_MAX+1],
        mguiMouseAreaDebugHud[MGUI_MOUSE_AREA_MAX+1];

script "MegaUI API" (int type, int arg1, int arg2, int arg3) CLIENTSIDE {
    switch(type) {

        // Debug toggle
        case -1:
            mguiIsDebug = arg1;
            MGUI_SetDebugAreaDisplayAll(mguiIsDebug);
            break;

        // End Mouse menu
        case 0:
            mguiIsMouseMenuRunning = false;
            if(mguiIsDebug)
                MGUI_SetDebugAreaDisplayAll(false);
            break;

        // Delete Mouse area
        case 1:
            if(!mguiIsMouseMenuRunning) {
                MGUI_Log("Warning : you must be in a mouse menu to call DeleteMouseArea");
                SetResultValue(false);
                terminate;
            }
            for(int i = 0; i < mguiMouseAreaCount; i++) {
                if(mguiMouseAreaIds[i] == arg1) {
                    for(int j = i; j <= mguiMouseAreaCount; j++) {
                        mguiMouseAreaIds[j] =               mguiMouseAreaIds[j+1];
                        mguiMouseAreaX1[j] =                mguiMouseAreaX1[j+1];
                        mguiMouseAreaX2[j] =                mguiMouseAreaX2[j+1];
                        mguiMouseAreaY1[j] =                mguiMouseAreaY1[j+1];
                        mguiMouseAreaY2[j] =                mguiMouseAreaY2[j+1];
                        mguiMouseAreaDebugPos[j] =          mguiMouseAreaDebugPos[j+1];
                        mguiMouseAreaDebugSize[j] =         mguiMouseAreaDebugSize[j+1];
                        mguiMouseAreaDebugHud[j] =          mguiMouseAreaDebugHud[j+1];
                    }
                    mguiMouseAreaCount--;
                    MGUI_SetDebugAreaDisplay(mguiMouseAreaCount, false);
                }
            }
            break;

        // GetMouseSpeed
        case 2: mguiMouseSpeed = arg1; break;

        // SetCustomMouse
        case 3:
            mguiMouseGraphic = arg1;
            mguiMouseOffsetX = arg2 & 0xFFFF;
            mguiMouseOffsetY = arg2>>16;
            mguiMouseHudWidth = arg3 & 0xFFFF;
            mguiMouseHudHeight = arg3>>16;
            break;

        // GetMouseX
        case 4: SetResultValue(mguiMouseX); break;

        // SetMouseX
        case 5: mguiMouseX = MGUI_Clamp(arg1, 0, 1.0); break;

        // GetMouseY
        case 6: SetResultValue(mguiMouseY); break;

        // SetMouseY
        case 7: mguiMouseY = MGUI_Clamp(arg1, 0, 1.0); break;
    }
}

script "MegaUI SetMouseArea API" (int areaId, int arg1, int arg2, int arg3) CLIENTSIDE {
    if(!mguiIsMouseMenuRunning) {
        MGUI_Log("Warning : you must be in a mouse menu to call SetMouseArea");
        SetResultValue(false);
        terminate;
    }
    if(areaId == MGUI_NULL_AREA) {
        MGUI_Log(StrParam(s:"Warning : tried to register mouse area with areaId = ", d:MGUI_NULL_AREA, 
            s:". It's the id used for the null area ; you can not use it."));
        SetResultValue(false);
        terminate;
    }
    int slot = -1;
    for(int i = 0; i < mguiMouseAreaCount; i++){
        if(mguiMouseAreaIds[i] == areaId) {
            slot = i;
            break;
        }
    }
    if(slot == -1) {
        if(mguiMouseAreaCount == MGUI_MOUSE_AREA_MAX) {
            MGUI_Log(StrParam(s:"Warning : can't register mouse area, the ", d:MGUI_MOUSE_AREA_MAX, s:" limit is reached!"));
            SetResultValue(false);
            terminate;
        }
        else {
            slot = mguiMouseAreaCount;
            mguiMouseAreaCount++;
            mguiMouseAreaIds[slot] = areaId;
        }
    }

    int x = arg1 & 0xFFFF,
        y = arg1 >> 16,
        width = arg2 & 0xFFFF,
        height = arg2 >> 16,
        hudWidth = arg3 & 0xFFFF,
        hudHeight = arg3 >> 16;
    x -= (width>>1);
    y -= (height>>1);

    // Registers bounding box as [0.0, 1.0] (normalized) values
    mguiMouseAreaX1[slot] = FixedDiv(x<<16, hudWidth<<16);
    mguiMouseAreaX2[slot] = FixedDiv((x+width)<<16, hudWidth<<16);
    mguiMouseAreaY1[slot] = FixedDiv(y<<16, hudHeight<<16);
    mguiMouseAreaY2[slot] = FixedDiv((y+height)<<16,hudHeight<<16);
    mguiMouseAreaDebugPos[slot] = (y<<16)|x;
    mguiMouseAreaDebugSize[slot] = arg2;
    mguiMouseAreaDebugHud[slot] = arg3;
    if(mguiIsDebug)
        MGUI_SetDebugAreaDisplay(slot, true);
    SetResultValue(true);
}

// The mouse draw/area poll thread
script "MegaUI Mouse Menu" (int scriptName) CLIENTSIDE {
    if(!CheckScript(scriptName, true)) {
        MGUI_Log(StrParam( s:"Can't start Mouse Menu : the [\c[31]", s:scriptName, s:"\c-] provided callback script does not exist!"));
        SetResultValue(false);
        terminate;
    }
    else if(mguiIsMouseMenuRunning) {
        MGUI_Log("Warning : tried to start Mouse Menu while one was already running.");
        SetResultValue(false);
        terminate;
    }
    SetResultValue(true);
    mguiIsMouseMenuRunning =   true; 
    mguiMouseScript =       scriptName;
    mguiMouseAreaCount =    0;
    for(int i = 0; i < MGUI_MOUSE_AREA_MAX+1; i++)
        mguiMouseAreaIds[i] = MGUI_NULL_AREA;

    int prevArea = MGUI_NULL_AREA, 
        area = prevArea;
    SetMouseX(0.5);
    SetMouseY(0.5);
    while(mguiIsMouseMenuRunning) {
        if(mguiIsDebug)
            Draw(area == MGUI_NULL_AREA ? "MEGAUI_Y" : "MEGAUI_X", (GetMouseX()*MGUI_HUD_WIDTH)>>16, (GetMouseY()*MGUI_HUD_HEIGHT)>>16, MGUI_HUD_WIDTH, MGUI_HUD_HEIGHT, 1.0);
        Draw(mguiMouseGraphic,  
            (MGUI_Roundf(GetMouseX()*mguiMouseHudWidth)>>16) + mguiMouseOffsetX, 
            (MGUI_Roundf(GetMouseY()*mguiMouseHudHeight)>>16) + mguiMouseOffsetY, 
            mguiMouseHudWidth, mguiMouseHudHeight, 1.0);

        area = MGUI_GetMouseAreaId();

		// Event detection
        int input = GetPlayerInput(-1, INPUT_BUTTONS);
		int inputDelta = GetPlayerInput(-1, INPUT_OLDBUTTONS) ^ input;

        if(inputDelta & MGUI_MOUSE_INTERACT)
			ACS_NamedExecuteWithResult(mguiMouseScript, (input & MGUI_MOUSE_INTERACT) ? MGUI_EVENT_DOWN : MGUI_EVENT_UP, area);
        else if(inputDelta & MGUI_MOUSE_ALT_INTERACT)
			ACS_NamedExecuteWithResult(mguiMouseScript, (input & MGUI_MOUSE_ALT_INTERACT) ? MGUI_EVENT_ALT_DOWN : MGUI_EVENT_ALT_UP, area);
        if(area != prevArea) {
            if(area != MGUI_NULL_AREA)      
                ACS_NamedExecuteWithResult(mguiMouseScript, MGUI_EVENT_ENTER, area);
            if(prevArea != MGUI_NULL_AREA)  {
                // Won't call EXIT event on an area that just got deleted
                for(i = 0; i < mguiMouseAreaCount; i++) 
                    if(mguiMouseAreaIds[i] == prevArea) { 
                        ACS_NamedExecuteWithResult(mguiMouseScript, MGUI_EVENT_EXIT, prevArea);
                        break;
                    }
            }
            prevArea = area;
        }

        // Mouse delta
        delay(1);
        int delta = GetRawMouseDeltaX();
        if(delta)
            SetMouseX(mguiMouseX - ((FixedMul(FixedMul(delta<<16, mguiMouseSpeed), 1.7)>>15)));
        delta = GetRawMouseDeltaY();
        if(delta)
            SetMouseY(mguiMouseY - ((FixedMul(FixedMul(delta<<16, mguiMouseSpeed), 1.7)>>15)));
    }
}

function int MGUI_GetMouseAreaId(void) {
    int x = GetMouseX(), 
        y = GetMouseY();
	int areaId = MGUI_NULL_AREA;
    for(int i = 0; i < mguiMouseAreaCount; i++) {
        // Check if within rectangle
        if(x >= mguiMouseAreaX1[i]) { if(x < mguiMouseAreaX2[i]) { if(y >= mguiMouseAreaY1[i]) { if(y < mguiMouseAreaY2[i]) {
            if(mguiMouseAreaIds[i] < areaId)
				areaId = mguiMouseAreaIds[i];
        } } } }
    }
    return areaId;
}

function void MGUI_SetDebugAreaDisplay(int slot, int state) {
    if(state) {
        int x = mguiMouseAreaDebugPos[slot] & 0xFFFF,
            y = mguiMouseAreaDebugPos[slot] >> 16,
            hudWidth = mguiMouseAreaDebugHud[slot] & 0xFFFF;
        Crop(x, y, mguiMouseAreaDebugSize[slot] & 0xFFFF, mguiMouseAreaDebugSize[slot] >> 16, hudWidth);
        Show(MGUI_DEBUG_AREA_DRAWID+slot, "MEGAUI_Z", x, y, hudWidth, mguiMouseAreaDebugHud[slot] >> 16, 0.3);
        Uncrop();
    }
    else
        Hide(MGUI_DEBUG_AREA_DRAWID+slot);
}

function void MGUI_SetDebugAreaDisplayAll(int state) {
    for(int i = 0; i < mguiMouseAreaCount; i++)
        MGUI_SetDebugAreaDisplay(i, state);
}
