
                //////////////////////////////////////////////////////////////
                //                                                          //
                //   ███╗   ███╗███████╗ ██████╗  █████╗     ██╗   ██╗██╗   //
                //   ████╗ ████║██╔════╝██╔════╝ ██╔══██╗    ██║   ██║██║   //
                //   ██╔████╔██║█████╗  ██║  ███╗███████║    ██║   ██║██║   //
                //   ██║╚██╔╝██║██╔══╝  ██║   ██║██╔══██║    ██║   ██║██║   //
                //   ██║ ╚═╝ ██║███████╗╚██████╔╝██║  ██║    ╚██████╔╝██║   //
                //   ╚═╝     ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝   //
                //                                                          //
                //////////////////////////////////////////////////////////////
                //                   Version 1.0.0                          //
                //////////////////////////////////////////////////////////////


// -------------------------------------------------------------------------------------------
//      General
// -------------------------------------------------------------------------------------------

/*
- To use MegaUI, copy this megaUI.acs file to your mod and use #include "megaUI.acs"
    - Optionally, copy MegaUI's graphics/debug content to your mod : it is needed to use debug mode MGUI_SetDebug() below
- All functions are expected to be run in CLIENTSIDE context (NamedExecuteClientScript, etc)
- Use NON-fixed ints for x/y position (160, 120 ; instead of 160.0, 120.0)
- hudWidth and hudHeight represent SetHudSize's "scaling" width/height parameters (i.e 320, 240)
*/

// Set Debug on/off. Debug displays MegaUI errors, and mouse areas' hitbox/crosshair on mouse's position
function void MGUI_SetDebug(bool state) { ACS_NamedExecuteWithResult("MegaUI API", -1, state); }

// -------------------------------------------------------------------------------------------
//      API ~ Rendering
// -------------------------------------------------------------------------------------------

// Draws a graphic on screen
function void Show(int hudMessageId, str graphic, int x, int y, int hudWidth, int hudHeight, int alpha) {
    MGUI_DrawCore(hudMessageId, "A", graphic, x, y, hudWidth, hudHeight, alpha, 0); 
}

// Draws a graphic on screen for 1 tic only
function void Draw(str graphic, int x, int y, int hudWidth, int hudHeight, int alpha) { 
    Show(0, graphic, x, y, hudWidth, hudHeight, alpha); 
}

// ShowText()/DrawText() flags
#DEFINE MGUI_CENTER 0x80000000 // Center text (SetHudSize's x |= 0.4)
#DEFINE MGUI_TYPEON 0x40000000 // Delayed text typing (HUDMSG_TYPEON). For example, for a 0.6s delay, use flags = (MGUI_TYPEON | 0.6)

// Draws text on screen
function void ShowText(int hudMessageId, str text, str font, int x, int y, int hudWidth, int hudHeight, int wrap, int alpha, int flags) {
    MGUI_DrawTextCore(hudMessageId, text, font, x, y, hudWidth, hudHeight, wrap, alpha, flags);
}

// Draws text on screen for 1 tic only
function void DrawText(str text, str font, int x, int y, int hudWidth, int hudHeight, int wrap, int alpha, int flags) { 
    ShowText(0, text, font, x, y, hudWidth, hudHeight, wrap, alpha, flags);
}

// Erase a Show() or ShowText() rendered element from screen
function void Hide(int hudMessageId) { 
    HudMessageBold(s:""; HUDMSG_PLAIN, hudMessageId, 0, 0, 0, 0, 0); 
}

// Shorthand for <count> consecutive Hide() calls, starting from <hudMessageId>
function void HideRange(int hudMessageId, int count) {
    for(int i = 0; i < count; i++) 
        Hide(hudMessageId+i);
}

// Make subsequent render calls not display pixels outside the given rectangle (SetHudClipRect). 
// hudWith is the same value as the element that will be cropped's hudWidth.
// Stop the effect with Uncrop()
function void Crop(int left, int top, int width, int height, int hudWidth) { 
    MGUI_CropCore(left, top, width, height, hudWidth, 0, false);
}

// Stop previous Crop()'s effect
function void Uncrop(void) {
    MGUI_CropCore(0, 0, 0, 0, 0, 0, false);
}

// SetAnchor values
#DEFINE MGUI_LEFT   1
#DEFINE MGUI_RIGHT  2

// Make subsequent Draw/Show calls keep a fixed offset from the left or right screen edge (based on anchorValue)
// Stop the effect with ClearAnchor()
function void SetAnchor(int anchorValue) { 
    MGUI_SetAnchorCore(anchorValue); 
}

function void ClearAnchor(void) {
    MGUI_SetAnchorCore(-1); 
}

// -------------------------------------------------------------------------------------------
//      API ~ Mouse Menu
// -------------------------------------------------------------------------------------------

#DEFINE MGUI_NULL_AREA                  0x7FFFFFFF

// Mouse Menu event type for callback script
#DEFINE MGUI_EVENT_ENTER                0 // On mouse enter area
#DEFINE MGUI_EVENT_EXIT                 1 // On mouse leave area
#DEFINE MGUI_EVENT_DOWN                 2 // On fire button press
#DEFINE MGUI_EVENT_UP                   3 // On fire button release
#DEFINE MGUI_EVENT_ALT_DOWN             4 // On altfire button press
#DEFINE MGUI_EVENT_ALT_UP               5 // On altfire button release

/* Enables mouse menu. It will send mouse events to the given @scriptName callback script with the arguments (int e, int areaId) :
    - @e event type
    - @areaId the mouse area id that triggered it
        - For fire/altfire button actions, if no area is hovered, areaId value will be MGUI_NULL_AREA
It returns false if could not start due to another mod already using mouse menu, or if callback script does not exist */
function bool   StartMouseMenu(str scriptName) {    return ACS_NamedExecuteWithResult("MegaUI Mouse Menu", scriptName); }

// Stops mouse menu
function void   EndMouseMenu(void) {                ACS_NamedExecuteWithResult("MegaUI API", 0); }

/*  Registers an area that sends mouse events. Width/height is the area's dimensions, as if it was a graphic file
    > areaId must be >= 0
    > When the mouse is within several areas, only the one with lowest areaId will trigger events (similar to hudMessage id priority) */
function void   SetMouseArea(int areaId, int x, int y, int hudWidth, int hudHeight, int width, int height) { 
    ACS_NamedExecuteWithResult("MegaUI SetMouseArea API", areaId, (y<<16)|(x+0x7FFF), (hudHeight<<16)|hudWidth, (MGUI_GetAnchor()<<28)|(height<<14)|width); 
}

// Unregisters an area
function void   DeleteMouseArea(int areaId) {       ACS_NamedExecuteWithResult("MegaUI API", 1, areaId); }

// Shorthand for <count> consecutive DeleteMouseArea() calls, starting from <areaId>
function void   DeleteMouseAreaRange(int areaId, int count) {
    for(int i = 0; i < count; i++) 
        DeleteMouseArea(areaId+i);
}

// Change mouse speed multiplier (default 1.0)
function void   SetMouseSpeed(int speed) {          ACS_NamedExecuteWithResult("MegaUI API", 2, speed); }

// Customize mouse's graphic / pixel offset from origin / graphic scale (Hud Size)
function void   SetCustomMouse(str graphic, int offsetX, int offsetY, int hudWidth, int hudHeight) { 
    ACS_NamedExecuteWithResult("MegaUI API", 3, graphic, ((offsetY+0x7FFF)<<16)|(offsetX+0x7FFF), (hudHeight<<16)|hudWidth); }

/* Mouse's position :
    - For a 4:3 screen resolution, value is [0.0, 1.0] 
    - Wider screens can go over, i.e [-0.3, 1.3] 
*/
function int    GetMouseX(void) {                   return ACS_NamedExecuteWithResult("MegaUI API", 4); }
function void   SetMouseX(int value) {              ACS_NamedExecuteWithResult("MegaUI API", 5, value); }
function int    GetMouseY(void) {                   return ACS_NamedExecuteWithResult("MegaUI API", 6); }
function void   SetMouseY(int value) {              ACS_NamedExecuteWithResult("MegaUI API", 7, value); }

// Get the physical mouse's position difference since previous tic (unitless)
function int    GetRawMouseDeltaX(void) {           return GetPlayerInput(-1, INPUT_YAW); }
function int    GetRawMouseDeltaY(void) {           return (GetPlayerInput(-1, INPUT_PITCH)*GetScreenWidth())/GetScreenHeight(); }

// -------------------------------------------------------------------------------------------
//      API ~ END
// -------------------------------------------------------------------------------------------



/*
// ---------------------------------------------------------------------------------------------------------------------------------------- //
// ---------------------------------------------------------------------------------------------------------------------------------------- //
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                            Internal       
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ---------------------------------------------------------------------------------------------------------------------------------------- //
// ---------------------------------------------------------------------------------------------------------------------------------------- //
*/

#DEFINE MGUI_HUD_WIDTH      320
#DEFINE MGUI_HUD_HEIGHT     240

#DEFINE MGUI_CROP_POS       -0x7FFF
#DEFINE MGUI_CROP_SIZE      0xFFFE

#DEFINE MGUI_ANCHOR_NONE    0

int                         mguiIsDebug = false,
                            mguiCropX = MGUI_CROP_POS,
                            mguiCropY = MGUI_CROP_POS,
                            mguiCropWidth = MGUI_CROP_SIZE,
                            mguiCropHeight = MGUI_CROP_SIZE,
                            mguiCropHudWidth = MGUI_HUD_WIDTH,
                            mguiAnchor = MGUI_ANCHOR_NONE,
                            mguiPlayerWidthCache = -1,
                            mguiPlayerHeightCache = -1,
                            mgui4to3Ratio = 1.0;

function void   MGUI_Log(str message) {             if(mguiIsDebug) log(s:"\c[v7][\c[x5] MegaUI \c[v7]] \c-",s:message); }
function int    MGUI_Min(int x, int y) {            return (x>y ? y : x); }
function int    MGUI_Max(int x, int y) {            return (x>y ? x : y); }
function int    MGUI_Clamp(int n, int l, int r) {   return MGUI_Max(MGUI_Min(n,r),l); }
function int    MGUI_Roundf(int n) {                return (n+0.5)&0xFFFF0000; }

// Calculates (screenWidth/screenHeight) / (4/3)
function int    MGUI_GetScreen4to3Ratio(void) {     
    if((GetScreenWidth() != mguiPlayerWidthCache) || (GetScreenHeight() != mguiPlayerHeightCache)) {
        mguiPlayerWidthCache = GetScreenWidth(),
        mguiPlayerHeightCache = GetScreenHeight(),
        mgui4to3Ratio = FixedDiv(FixedDiv(GetScreenWidth()<<16, GetScreenHeight()<<16),1.333333); 
    }
    return mgui4to3Ratio;
}

// Calculates x position with anchor modifier applied
function int    MGUI_GetAnchoredX(int x, int hudWidth, int anchor) { 
    if(anchor != MGUI_ANCHOR_NONE) {
        int screenOffset = (FixedMul(hudWidth << 16, MGUI_GetScreen4to3Ratio()) - (hudWidth<<16)) >> 17; 
        if(anchor == MGUI_LEFT)         x -= screenOffset;
        else if(anchor == MGUI_RIGHT)   x += screenOffset;
    }
    return x;
}

    ///////////////
    // Rendering //
    ///////////////


function void MGUI_DrawCore(int hudMessageId, str value, str font, int x, int y, int hudWidth, int hudHeight, int alpha, int flags) {
	SetHudSize(hudWidth, hudHeight, true);
	SetFont(font);
    x = MGUI_GetAnchoredX(x, hudWidth, mguiAnchor);
    if(flags & MGUI_TYPEON) {
        HudMessageBold(s:value; HUDMSG_PLAIN|HUDMSG_ALPHA|HUDMSG_TYPEON, hudMessageId, CR_UNTRANSLATED,
            (x << 16) | (flags & MGUI_CENTER ? 0.4 : 0), y<<16, 0x8000000, (flags & 0x0FFFFFFF), 0x80000000, alpha);
    }
    else {
        HudMessageBold(s:value; HUDMSG_PLAIN|HUDMSG_ALPHA, hudMessageId, CR_UNTRANSLATED,
            (x << 16) | (flags & MGUI_CENTER ? 0.4 : 0), y<<16, (hudMessageId ? 0x8000000 : 1873), alpha);
    }
}

function void MGUI_DrawTextCore(int hudMessageId, str text, str font, int x, int y, int hudWidth, int hudHeight, int wrap, int alpha, int flags) {
    if(wrap) 
        MGUI_CropCore(mguiCropX, mguiCropY, mguiCropWidth, mguiCropHeight, mguiCropHudWidth, wrap, true);
    MGUI_DrawCore(hudMessageId, text, font, x, y, hudWidth, hudHeight, alpha, flags);
    if(wrap) 
        MGUI_RestoreCrop();
}

function void MGUI_CropCore(int left, int top, int width, int height, int hudWidth, int wrap, bool isStateless) { 
    // Crop
    if(width) {
        int x = MGUI_GetAnchoredX(left, hudWidth, mguiAnchor);
        if(!isStateless) {
            mguiCropX = left,
            mguiCropY = top,
            mguiCropWidth = width,
            mguiCropHeight = height,
            mguiCropHudWidth = hudWidth;
        }
        SetHudClipRect(x, top, width, height, wrap);
    }

    // Uncrop
    else {
        if(!isStateless) {
            mguiCropX = MGUI_CROP_POS, 
            mguiCropY = MGUI_CROP_POS, 
            mguiCropWidth = MGUI_CROP_SIZE, 
            mguiCropHeight = MGUI_CROP_SIZE;
        }
        SetHudClipRect(0, 0, 0, 0, 0); 
    }
}

function void MGUI_RestoreCrop(void) {
    MGUI_CropCore(mguiCropX, mguiCropY, mguiCropWidth, mguiCropHeight, mguiCropHudWidth, 0, true);
}

function int MGUI_GetAnchor(void) {
    return mguiAnchor;
}

function void MGUI_SetAnchorCore(int anchorValue) {
    mguiAnchor = anchorValue;
    if(mguiCropX != MGUI_CROP_POS) // Refresh crop left (X) position
        MGUI_RestoreCrop();
}


    /////////////////
    // Mouse menu  //
    /////////////////

#DEFINE MGUI_MOUSE_AREA_MAX         256
#DEFINE MGUI_DEBUG_AREA_DRAWID      1
#DEFINE MGUI_DEBUG_AREA_DRAWID_END  MGUI_DEBUG_AREA_DRAWID+MGUI_MOUSE_AREA_MAX

#DEFINE MGUI_MOUSE_INTERACT         BT_ATTACK
#DEFINE MGUI_MOUSE_ALT_INTERACT     BT_ALTATTACK

int     mguiIsMouseMenuRunning =    false,
        mguiMouseGraphic =          "DOOMCURS",
        mguiMouseOffsetX =          7,
        mguiMouseOffsetY =          14,
        mguiMouseX =                0.5,
        mguiMouseY =                0.5,
        mguiMouseHudWidth =         MGUI_HUD_WIDTH,
        mguiMouseHudHeight =        MGUI_HUD_HEIGHT,
        mguiMouseSpeed =            1.0,
        mguiMouseScript =           "MegaUI Mouse Callback";

int     mguiMouseAreaCount = 0;

int     mguiMouseAreaIds[MGUI_MOUSE_AREA_MAX+1],
        mguiMouseAreaX1[MGUI_MOUSE_AREA_MAX+1],
        mguiMouseAreaX2[MGUI_MOUSE_AREA_MAX+1],
        mguiMouseAreaY1[MGUI_MOUSE_AREA_MAX+1],
        mguiMouseAreaY2[MGUI_MOUSE_AREA_MAX+1]; 

int     mguiMouseAreaDebugPosX[MGUI_MOUSE_AREA_MAX+1],
        mguiMouseAreaDebugPosY[MGUI_MOUSE_AREA_MAX+1],
        mguiMouseAreaDebugSizeAndAnchor[MGUI_MOUSE_AREA_MAX+1],
        mguiMouseAreaDebugHud[MGUI_MOUSE_AREA_MAX+1];

script "MegaUI API" (int type, int arg1, int arg2, int arg3) CLIENTSIDE {
    switch(type) {

        // Debug toggle
        case -1:
            mguiIsDebug = arg1;
            MGUI_SetDebugAreaDisplayAll(mguiIsDebug);
            break;

        // End Mouse menu
        case 0:
            mguiIsMouseMenuRunning = false;
            if(mguiIsDebug)
                MGUI_SetDebugAreaDisplayAll(false);
            break;

        // Delete Mouse area
        case 1:
            if(!mguiIsMouseMenuRunning) {
                MGUI_Log("Warning : you must be in a mouse menu to call DeleteMouseArea");
                SetResultValue(false);
                terminate;
            }
            for(int i = 0; i < mguiMouseAreaCount; i++) {
                if(mguiMouseAreaIds[i] == arg1) {
                    for(int j = i; j <= mguiMouseAreaCount; j++) {
                        mguiMouseAreaIds[j] =               mguiMouseAreaIds[j+1];
                        mguiMouseAreaX1[j] =                mguiMouseAreaX1[j+1];
                        mguiMouseAreaX2[j] =                mguiMouseAreaX2[j+1];
                        mguiMouseAreaY1[j] =                mguiMouseAreaY1[j+1];
                        mguiMouseAreaY2[j] =                mguiMouseAreaY2[j+1];
                        mguiMouseAreaDebugPosX[j] =         mguiMouseAreaDebugPosX[j+1];
                        mguiMouseAreaDebugPosY[j] =         mguiMouseAreaDebugPosY[j+1];
                        mguiMouseAreaDebugSizeAndAnchor[j] =mguiMouseAreaDebugSizeAndAnchor[j+1];
                        mguiMouseAreaDebugHud[j] =          mguiMouseAreaDebugHud[j+1];
                    }
                    mguiMouseAreaCount--;
                    MGUI_SetDebugAreaDisplay(mguiMouseAreaCount, false);
                }
            }
            break;

        // GetMouseSpeed
        case 2: mguiMouseSpeed = arg1; break;

        // SetCustomMouse
        case 3:
            mguiMouseGraphic = arg1,
            mguiMouseOffsetX = (arg2 & 0xFFFF)-0x7FFF,
            mguiMouseOffsetY = (arg2>>16)-0x7FFF,
            mguiMouseHudWidth = arg3 & 0xFFFF,
            mguiMouseHudHeight = arg3>>16;
            break;

        // GetMouseX
        case 4: SetResultValue(mguiMouseX); break;

        // SetMouseX
        case 5: 
            int screenExtension = (MGUI_GetScreen4to3Ratio()-1.0)>>1;
            mguiMouseX = MGUI_Clamp(arg1, 0-screenExtension, 1.0+screenExtension); 
            break;

        // GetMouseY
        case 6: SetResultValue(mguiMouseY); break;

        // SetMouseY
        case 7: mguiMouseY = MGUI_Clamp(arg1, 0, 1.0); break;
    }
}

script "MegaUI SetMouseArea API" (int areaId, int arg1, int arg2, int arg3) CLIENTSIDE {
    if(!mguiIsMouseMenuRunning) {
        MGUI_Log("Warning : you must be in a mouse menu to call SetMouseArea");
        SetResultValue(false);
        terminate;
    }
    if(areaId == MGUI_NULL_AREA) {
        MGUI_Log(StrParam(s:"Warning : tried to register mouse area with areaId = ", d:MGUI_NULL_AREA, 
            s:". It's the id used for the null area ; you can not use it."));
        SetResultValue(false);
        terminate;
    }
    int slot = -1;
    for(int i = 0; i < mguiMouseAreaCount; i++){
        if(mguiMouseAreaIds[i] == areaId) {
            slot = i;
            break;
        }
    }
    if(slot == -1) {
        if(mguiMouseAreaCount == MGUI_MOUSE_AREA_MAX) {
            MGUI_Log(StrParam(s:"Warning : can't register mouse area, the ", d:MGUI_MOUSE_AREA_MAX, s:" limit is reached!"));
            SetResultValue(false);
            terminate;
        }
        else {
            slot = mguiMouseAreaCount;
            mguiMouseAreaCount++;
            mguiMouseAreaIds[slot] = areaId;
        }
    }

    int x =         (arg1 & 0xFFFF)-0x7FFF,
        y =         arg1 >> 16,
        hudWidth =  arg2 & 0xFFFF,
        hudHeight = arg2 >> 16,
        width =     (arg3 & 0x3FFF),        // 14 bits
        height =    (arg3 >> 14) & 0x3FFF,  // 14 bits
        anchor =    (arg3 >> 28) & 0x3;     // 2 bits
    x -= (width>>1);
    y -= (height>>1);
    int anchoredX = MGUI_GetAnchoredX(x, hudWidth, anchor);

    mguiMouseAreaX1[slot] = FixedDiv(anchoredX<<16, hudWidth<<16);
    mguiMouseAreaX2[slot] = FixedDiv((anchoredX+width)<<16, hudWidth<<16);
    mguiMouseAreaY1[slot] = FixedDiv(y<<16, hudHeight<<16);
    mguiMouseAreaY2[slot] = FixedDiv((y+height)<<16,hudHeight<<16);
    mguiMouseAreaDebugPosX[slot] = x;
    mguiMouseAreaDebugPosY[slot] = y;
    mguiMouseAreaDebugHud[slot] = arg2;
    mguiMouseAreaDebugSizeAndAnchor[slot] = arg3;
    if(mguiIsDebug)
        MGUI_SetDebugAreaDisplay(slot, true);
    SetResultValue(true);
}

// The mouse draw/area poll thread
script "MegaUI Mouse Menu" (int scriptName) CLIENTSIDE {
    if(!CheckScript(scriptName, true)) {
        MGUI_Log(StrParam( s:"Can't start Mouse Menu : the [\c[31]", s:scriptName, s:"\c-] provided callback script does not exist!"));
        SetResultValue(false);
        terminate;
    }
    else if(mguiIsMouseMenuRunning) {
        MGUI_Log("Warning : tried to start Mouse Menu while one was already running.");
        SetResultValue(false);
        terminate;
    }
    SetResultValue(true);
    mguiIsMouseMenuRunning =    true; 
    mguiMouseScript =           scriptName;
    mguiMouseAreaCount =    0;
    for(int i = 0; i < MGUI_MOUSE_AREA_MAX+1; i++)
        mguiMouseAreaIds[i] = MGUI_NULL_AREA;

    int prevArea = MGUI_NULL_AREA, 
        area = prevArea;
    SetMouseX(0.5);
    SetMouseY(0.5);
    while(mguiIsMouseMenuRunning) {
        if(mguiIsDebug)
            Draw(area == MGUI_NULL_AREA ? "MEGAUI_Y" : "MEGAUI_X", 
                (GetMouseX()*MGUI_HUD_WIDTH)>>16, (GetMouseY()*MGUI_HUD_HEIGHT)>>16, 
                MGUI_HUD_WIDTH, MGUI_HUD_HEIGHT, 1.0);

        Draw(mguiMouseGraphic,  
            (MGUI_Roundf(GetMouseX()*mguiMouseHudWidth)>>16) + mguiMouseOffsetX, 
            (MGUI_Roundf(GetMouseY()*mguiMouseHudHeight)>>16) + mguiMouseOffsetY, 
            mguiMouseHudWidth, 
            mguiMouseHudHeight, 
            1.0);

        area = MGUI_GetMouseAreaId();

		// Event detection
        int input = GetPlayerInput(-1, INPUT_BUTTONS);
		int inputDelta = GetPlayerInput(-1, INPUT_OLDBUTTONS) ^ input;

        if(inputDelta & MGUI_MOUSE_INTERACT)
			ACS_NamedExecuteWithResult(mguiMouseScript, (input & MGUI_MOUSE_INTERACT) ? MGUI_EVENT_DOWN : MGUI_EVENT_UP, area);
        else if(inputDelta & MGUI_MOUSE_ALT_INTERACT)
			ACS_NamedExecuteWithResult(mguiMouseScript, (input & MGUI_MOUSE_ALT_INTERACT) ? MGUI_EVENT_ALT_DOWN : MGUI_EVENT_ALT_UP, area);
        if(area != prevArea) {
            if(prevArea != MGUI_NULL_AREA)  {
                // Won't call EXIT event on an area that just got deleted
                for(i = 0; i < mguiMouseAreaCount; i++) 
                    if(mguiMouseAreaIds[i] == prevArea) { 
                        ACS_NamedExecuteWithResult(mguiMouseScript, MGUI_EVENT_EXIT, prevArea);
                        break;
                    }
            }
            if(area != MGUI_NULL_AREA)      
                ACS_NamedExecuteWithResult(mguiMouseScript, MGUI_EVENT_ENTER, area);
            prevArea = area;
        }

        // Mouse delta
        delay(1);
        int delta = GetRawMouseDeltaX();
        if(delta)
            SetMouseX(mguiMouseX - ((FixedMul(FixedMul(delta<<16, mguiMouseSpeed), 1.7)>>15)));
        delta = GetRawMouseDeltaY();
        if(delta)
            SetMouseY(mguiMouseY - ((FixedMul(FixedMul(delta<<16, mguiMouseSpeed), 1.7)>>15)));
    }
}

function int MGUI_GetMouseAreaId(void) {
    int x = GetMouseX(), 
        y = GetMouseY();
	int areaId = MGUI_NULL_AREA;
    for(int i = 0; i < mguiMouseAreaCount; i++) {
        // Check if within rectangle
        if(x >= mguiMouseAreaX1[i]) { if(x < mguiMouseAreaX2[i]) { if(y >= mguiMouseAreaY1[i]) { if(y < mguiMouseAreaY2[i]) {
            if(mguiMouseAreaIds[i] < areaId)
				areaId = mguiMouseAreaIds[i];
        } } } }
    }
    return areaId;
}

function void MGUI_SetDebugAreaDisplay(int slot, int state) {
    if(state) {
        int x = mguiMouseAreaDebugPosX[slot],
            y = mguiMouseAreaDebugPosY[slot],
            hudWidth = mguiMouseAreaDebugHud[slot] & 0xFFFF;
        int tmpAnchor = mguiAnchor;
        SetAnchor((mguiMouseAreaDebugSizeAndAnchor[slot] >> 28) & 0x3);
        MGUI_CropCore(x, y, mguiMouseAreaDebugSizeAndAnchor[slot] & 0x3FFF, (mguiMouseAreaDebugSizeAndAnchor[slot] >> 14) & 0x3FFF, hudWidth, 0, true);
        Show(MGUI_DEBUG_AREA_DRAWID+slot, "MEGAUI_Z", x, y, hudWidth, mguiMouseAreaDebugHud[slot] >> 16, 0.8);
        SetAnchor(tmpAnchor);
        MGUI_RestoreCrop();
    }
    else
        Hide(MGUI_DEBUG_AREA_DRAWID+slot);
}

function void MGUI_SetDebugAreaDisplayAll(int state) {
    for(int i = 0; i < mguiMouseAreaCount; i++)
        MGUI_SetDebugAreaDisplay(i, state);
}

// Stops mouse menu on game enter / spectate since the script gets interrupted 
script "MegaUI ENTER" ENTER CLIENTSIDE {
    if(ConsolePlayerNumber() == PlayerNumber())
        EndMouseMenu();
}

script "MegaUI DISCONNECT" (int player) DISCONNECT CLIENTSIDE {
    if(ConsolePlayerNumber() == player)
        EndMouseMenu();
}