
function void MGUI_EditorLog(str message) { 
    log(s:"\c[v7][\c[z2] MegaUI Editor \c[v7]] \c-",s:message); 
}

// https://cleantextkit.com/remove-timestamps/

#DEFINE MGUI_EDITOR_SFX_NO             "misc/wanaan"
#DEFINE MGUI_EDITOR_SFX_STAMP_ADD      "misc/mercuryconveyorswitch"
#DEFINE MGUI_EDITOR_SFX_STAMP_REMOVE   "misc/eclipsedarkshot"
#DEFINE MGUI_EDITOR_SFX_TOGGLE         "misc/cursorq"
#DEFINE MGUI_EDITOR_SFX_RESET          "misc/fakereloadshort"
#DEFINE MGUI_EDITOR_SFX_BRUSH          "misc/venusdrip"

#DEFINE MGUI_EDITOR_MODE_SELECT         0
#DEFINE MGUI_EDITOR_MODE_MOVE           1
#DEFINE MGUI_EDITOR_MODE_SCALE          2
#DEFINE MGUI_EDITOR_MODE_WRAP           3

#DEFINE MGUI_EDITOR_MOUSE_DELTA        0.002
#DEFINE MGUI_EDITOR_SCALE_DELTA        1.03

bool    mguiEditorIsRunning,
        mguiEditorIsUniformScale,
        mguiEditorIsTextBrush;
str     mguiEditorBrushContent;
int     mguiEditorBrushXFactor,
        mguiEditorBrushYFactor,
        mguiEditorBrushFont,
        mguiEditorBrushWrap,
        mguiEditorMode;

// X/Y [0, 1.0] position, or XScale/YScale multiplier, into HUD dimension
function int MGUI_FactorToHud(int factor, int hud) { return (factor * hud)>>16; }



function void MGUI_SetEditorMode(int mode) {
    mguiEditorMode = mode;
    switch(mode) {

        case MGUI_EDITOR_MODE_SELECT:
            SetMouseCursor("MEGAUI_3");
            SetMouseOffset(6, 8);
            break;

        case MGUI_EDITOR_MODE_MOVE:
            SetMouseCursor("MEGAUI_4");
            SetMouseOffset(0, 0);
            SetMouseSpeed(1.0);
            break;

        case MGUI_EDITOR_MODE_SCALE:
            SetMouseCursor("MEGAUI_5");
            SetMouseSpeed(0.0);
            break;

        case MGUI_EDITOR_MODE_WRAP:
            SetMouseCursor("MEGAUI_7");
            SetMouseSpeed(0.0);
            break;
    }
}


function void MGUIEditor_SetTextBrush(bool state) {
    mguiEditorIsTextBrush = state;
    MGUI_Play(MGUI_EDITOR_SFX_TOGGLE);
    log(s:"text brush ", d:state);
}

script "MegaUI Editor" (void) CLIENTSIDE {
    if(!StartMouseMenu("MegaUI Editor Event")) {
        MGUI_EditorLog("There's already a mouse menu open.");
        terminate;
    }
    mguiEditorIsRunning = true;
    mguiEditorIsUniformScale = true;
    mguiEditorBrushFont = "SMALLFONT";
    MGUIEditor_SetTextBrush(false);
    mguiEditorBrushWrap = 0;
    int prevMouseX, prevMouseY, mouseX, mouseY;
    ACS_NamedExecuteWithResult("core_freezeplayer",0,true);

    MGUI_SetEditorMode(MGUI_EDITOR_MODE_SELECT);

    while(true) {
        mouseX = GetMouseX();
        mouseY = GetMouseY();
        int input = GetPlayerInput(-1, INPUT_BUTTONS);
        int prevInput = GetPlayerInput(-1, INPUT_OLDBUTTONS);
        int pressedInput = (input ^ prevInput) & ~prevInput;
        MGUI_EditorSpecialInputCheck(pressedInput, prevInput);

        // Stamp Move mode
        if(mguiEditorMode == MGUI_EDITOR_MODE_MOVE) {
            // Keyboard WASD 
            if(input & BT_MOVELEFT)       SetMouseX(mouseX-MGUI_EDITOR_MOUSE_DELTA);
            else if(input & BT_MOVERIGHT) SetMouseX(mouseX+MGUI_EDITOR_MOUSE_DELTA);
            if(input & BT_FORWARD)        SetMouseY(mouseY-MGUI_EDITOR_MOUSE_DELTA);
            else if(input & BT_BACK)      SetMouseY(mouseY+MGUI_EDITOR_MOUSE_DELTA);
        }
        // Stamp Scale mode
        else if(mguiEditorMode == MGUI_EDITOR_MODE_SCALE) {
            // Mouse
            int rawMouseDeltaX = GetRawMouseDeltaX()<<4;
            int rawMouseDeltaY = GetRawMouseDeltaY()<<4;
            if((rawMouseDeltaX > 0) | (rawMouseDeltaY > 0)) {
                if(mguiEditorIsUniformScale) {
                    int tmp = MGUI_Max(rawMouseDeltaX, rawMouseDeltaY);
                    mguiEditorBrushXFactor = FixedMul(mguiEditorBrushXFactor, 1.0 + tmp);
                    mguiEditorBrushYFactor = FixedMul(mguiEditorBrushYFactor, 1.0 + tmp);
                }
                else {
                    if(rawMouseDeltaX > 0)  mguiEditorBrushXFactor = FixedMul(mguiEditorBrushXFactor, 1.0 + rawMouseDeltaX);
                    if(rawMouseDeltaY > 0)  mguiEditorBrushYFactor = FixedMul(mguiEditorBrushYFactor, 1.0 + rawMouseDeltaY);
                }
            }
            else if((rawMouseDeltaX < 0) | (rawMouseDeltaY < 0)) {
                if(mguiEditorIsUniformScale) {
                    tmp = MGUI_Min(rawMouseDeltaX, rawMouseDeltaY);
                    mguiEditorBrushXFactor = FixedDiv(mguiEditorBrushXFactor, 1.0 - tmp);
                    mguiEditorBrushYFactor = FixedDiv(mguiEditorBrushYFactor, 1.0 - tmp);
                }
                else {
                    if(rawMouseDeltaX < 0)  mguiEditorBrushXFactor = FixedDiv(mguiEditorBrushXFactor, 1.0 - rawMouseDeltaX);
                    if(rawMouseDeltaY < 0)  mguiEditorBrushYFactor = FixedDiv(mguiEditorBrushYFactor, 1.0 - rawMouseDeltaY);
                }
            }

            // Keyboard WASD 
            if(input & (BT_MOVELEFT|BT_FORWARD)) {
                if((input & BT_MOVELEFT) | mguiEditorIsUniformScale)
                    mguiEditorBrushXFactor = FixedMul(mguiEditorBrushXFactor, MGUI_EDITOR_SCALE_DELTA);
                if((input & BT_FORWARD) | mguiEditorIsUniformScale)         
                    mguiEditorBrushYFactor = FixedMul(mguiEditorBrushYFactor, MGUI_EDITOR_SCALE_DELTA);
            }
            else if(input & (BT_MOVERIGHT|BT_BACK)) {
                if((input & BT_MOVERIGHT)|mguiEditorIsUniformScale)         
                    mguiEditorBrushXFactor = FixedDiv(mguiEditorBrushXFactor, MGUI_EDITOR_SCALE_DELTA);
                if((input & BT_BACK)|mguiEditorIsUniformScale)         
                    mguiEditorBrushYFactor = FixedDiv(mguiEditorBrushYFactor, MGUI_EDITOR_SCALE_DELTA);
            }
        }
        else if(mguiEditorMode == MGUI_EDITOR_MODE_WRAP) {
            rawMouseDeltaX = GetRawMouseDeltaX()<<2;
            if(rawMouseDeltaX)
                mguiEditorBrushWrap = MGUI_Clamp(mguiEditorBrushWrap-rawMouseDeltaX, 0.01, 1.0);
            if(input & BT_MOVELEFT)
                mguiEditorBrushWrap = MGUI_Max(mguiEditorBrushWrap-0.006, 0.01);
            else if(input & BT_MOVERIGHT)
                mguiEditorBrushWrap = MGUI_Min(mguiEditorBrushWrap+0.006, 1.0);
        }


        if(mguiEditorMode != MGUI_EDITOR_MODE_SELECT) {

            int hudWidth = MGUI_FactorToHud(mguiEditorBrushXFactor, MGUI_HUD_WIDTH), 
                hudHeight = MGUI_FactorToHud(mguiEditorBrushYFactor, MGUI_HUD_HEIGHT),
                x = (mouseX*hudWidth)>>16,
                y = (mouseY*hudHeight)>>16;


            if(mguiEditorIsTextBrush)
                DrawText(mguiEditorBrushContent, mguiEditorBrushFont, x, y, hudWidth, hudHeight, 
                    MGUI_FactorToHud(mguiEditorBrushWrap, hudWidth), 1.0);
            else
                Draw(mguiEditorBrushContent, x, y, hudWidth, hudHeight, 1.0);
        }
        delay(1);
        prevMouseX = mouseX;
        prevMouseY = mouseY;
    }
    ACS_NamedExecuteWithResult("core_freezeplayer",0,false);
    mguiEditorIsRunning = false;
    EndMouseMenu();
}


int fonts[2] = { "SMALLFONT", "CONFONT" };

script "defont" (int font) {
    mguiEditorBrushFont = fonts[font];

}

script "MegaUI Editor Chat" (int type, int message, int arg2) EVENT {
    if(!mguiEditorIsRunning)
        terminate;;
    if (type == GAMEEVENT_CHAT) {
        MGUIEditor_SetTextBrush(false);
        mguiEditorBrushWrap = 0;
        MGUI_EditStamp(GetChatMessage(message, 0), 1.0, 1.0, mguiEditorBrushFont, 0);
    }
}


function void MGUI_EditorSpecialInputCheck(int input, int prevInput) {
    if(input & BT_RELOAD) {
        mguiEditorBrushXFactor = 1.0;
        mguiEditorBrushYFactor = 1.0;
        mguiEditorBrushWrap = 1.0;
        MGUI_Play(MGUI_EDITOR_SFX_RESET);
        MGUI_EditorLog("Reset scale and text wrap.");
    }
    if(input & BT_SHOWSCORES) {
        MGUI_Play(MGUI_EDITOR_SFX_TOGGLE);
        mguiEditorIsUniformScale = !mguiEditorIsUniformScale;
        MGUI_EditorLog(strParam(s:"Uniform scale : ", d:mguiEditorIsUniformScale));
    }
    if(mguiEditorMode != MGUI_EDITOR_MODE_SELECT && mguiEditorMode != MGUI_EDITOR_MODE_SCALE) {
        if(input & BT_JUMP) {
            if(mguiEditorMode != MGUI_EDITOR_MODE_WRAP)
                MGUI_SetEditorMode(MGUI_EDITOR_MODE_WRAP);
            else
                MGUI_SetEditorMode(MGUI_EDITOR_MODE_MOVE);
        }
    }
    if(mguiEditorMode != MGUI_EDITOR_MODE_SELECT && (input & BT_CROUCH)) {
        MGUIEditor_SetTextBrush(!mguiEditorIsTextBrush);
        mguiEditorBrushWrap = 1.0;
        MGUI_EditorLog(strParam(s:"Toggle text brush :", d:mguiEditorIsTextBrush));
    }
}

// -------------------------------------------------------------------------------------------
//      Stamps
// -------------------------------------------------------------------------------------------

#DEFINE MGUI_EDITOR_STAMP_MAX              256
#DEFINE MGUI_EDITOR_STAMP_DRAWID           MGUI_DEBUG_AREA_DRAWID_END
#DEFINE MGUI_EDITOR_STAMP_DRAWID_END       MGUI_EDITOR_STAMP_DRAWID + (MGUI_EDITOR_STAMP_MAX * 2) // 1 image and 1 "..." edit icon
#DEFINE MGUI_DRAWID                        MGUI_EDITOR_STAMP_DRAWID_END
#DEFINE MGUI_EDITOR_STAMP_HOOK_ALPHA       0.4

int mguiEditorStampCount = 0;
int mguiEditorStampContent[MGUI_EDITOR_STAMP_MAX+1]; 
int mguiEditorStampX[MGUI_EDITOR_STAMP_MAX+1]; 
int mguiEditorStampY[MGUI_EDITOR_STAMP_MAX+1]; 
int mguiEditorStampXFactor[MGUI_EDITOR_STAMP_MAX+1]; 
int mguiEditorStampYFactor[MGUI_EDITOR_STAMP_MAX+1]; 
// used by text only
int mguiEditorStampFont[MGUI_EDITOR_STAMP_MAX+1];
int mguiEditorStampWrap[MGUI_EDITOR_STAMP_MAX+1];


function bool MGUIEditor_IsText(int slot) { return mguiEditorStampWrap[slot] != 0; }
function int MGUI_GetStampContentId(int slot) { return (MGUI_EDITOR_STAMP_DRAWID_END - 1) - (slot<<1); }
function int MGUI_GetStampContentSlot(int stampContentId) { return ((MGUI_EDITOR_STAMP_DRAWID_END - 1) - stampContentId)>>1; }
    
function void MGUI_SetStamp(int slot, str content, int x, int y, int xFactor, int yFactor, str font, int wrap) {
    mguiEditorStampContent[slot] =      content;
    mguiEditorStampX[slot] =            x;
    mguiEditorStampY[slot] =            y;
    mguiEditorStampXFactor[slot] =      xFactor;
    mguiEditorStampYFactor[slot] =      yFactor;
    mguiEditorStampFont[slot] =         font;
    mguiEditorStampWrap[slot] =         wrap;

    int id = MGUI_GetStampContentId(slot);

    int hudWidth = MGUI_FactorToHud(xFactor, MGUI_HUD_WIDTH),
        hudHeight = MGUI_FactorToHud(yFactor, MGUI_HUD_HEIGHT);

    if(MGUIEditor_IsText(slot)) 
        ShowText(id, content, font, (x*hudWidth)>>16, (y*hudHeight)>>16, hudWidth, hudHeight, MGUI_FactorToHud(wrap, hudWidth), 1.0);
    else
        Show(id, content,           (x*hudWidth)>>16, (y*hudHeight)>>16, hudWidth, hudHeight, 1.0);

    SetMouseArea(id, (x*320)>>16, (y*240)>>16, 16, 16, 320, 240);
    MGUI_DrawStampHook(id, MGUI_EDITOR_STAMP_HOOK_ALPHA);
}

function void MGUI_RemoveStamp(int stampId) {
    for(int slotA = 0; slotA < mguiEditorStampCount; slotA++) {
        if(MGUI_GetStampContentId(slotA) == stampId) {

            for(int slotB = slotA; slotB < mguiEditorStampCount; slotB++) {
                MGUI_SetStamp(slotB, 
                    mguiEditorStampContent[slotB+1], 
                    mguiEditorStampX[slotB+1], 
                    mguiEditorStampY[slotB+1], 
                    mguiEditorStampXFactor[slotB+1], 
                    mguiEditorStampYFactor[slotB+1],
                    mguiEditorStampFont[slotB+1],
                    mguiEditorStampWrap[slotB+1]
                );
            }

            // Erase the last one
            int id = MGUI_GetStampContentId(mguiEditorStampCount-1);
            DeleteMouseArea(id);
            Hide(id);
            Hide(id-1);
            mguiEditorStampCount--;
            return;
        }
    }
}


function void MGUI_EditStamp(int content, int xFactor, int yFactor, str font, int wrap) {
    MGUI_Play(MGUI_EDITOR_SFX_BRUSH);
    mguiEditorBrushContent = content; 
    mguiEditorBrushXFactor = xFactor;
    mguiEditorBrushYFactor = yFactor;
    mguiEditorBrushFont = font;
    mguiEditorBrushWrap = wrap;
    MGUI_SetEditorMode(MGUI_EDITOR_MODE_MOVE);
}

// -------------------------------------------------------------------------------------------
//      Misc / utils
// -------------------------------------------------------------------------------------------

function void MGUI_Play(str sound) { LocalAmbientSound(sound,127); }




















function void MGUI_DrawStampHook(int areaId, int alpha) {
    int slot = MGUI_GetStampContentSlot(areaId);
    Show(areaId-1, "MEGAUI_6", (mguiEditorStampX[slot]*320)>>16, (mguiEditorStampY[slot]*240)>>16, 320, 240, alpha);
}


script "MegaUI Editor Event" (int e, int areaId) CLIENTSIDE {
    switch(e) {

        // Mouse enters area
        case MGUI_EVENT_ENTER:
            MGUI_DrawStampHook(areaId, 1.0);
            break;

        // Mouse exits area
        case MGUI_EVENT_EXIT:
            MGUI_DrawStampHook(areaId, MGUI_EDITOR_STAMP_HOOK_ALPHA);
            break;

        // Left click press
        case MGUI_EVENT_DOWN:
            switch(mguiEditorMode) {
                case MGUI_EDITOR_MODE_SELECT:
                    if(areaId != MGUI_AREA_NULL) {
                        int daSlot = MGUI_GetStampContentSlot(areaId);
                        MGUI_EditStamp(
                            mguiEditorStampContent[daSlot], 
                            mguiEditorStampXFactor[daSlot], 
                            mguiEditorStampYFactor[daSlot], 
                            mguiEditorStampFont[daSlot], 
                            mguiEditorStampWrap[daSlot]
                        );
                        MGUIEditor_SetTextBrush(MGUIEditor_IsText(daSlot));
                        mguiEditorBrushWrap = mguiEditorStampWrap[daSlot];
                        MGUI_RemoveStamp(areaId);
                    }
                    break;
                case MGUI_EDITOR_MODE_MOVE:
                    int slot = mguiEditorStampCount;
                    if(slot == MGUI_EDITOR_STAMP_MAX)
                        MGUI_Play(MGUI_EDITOR_SFX_NO);
                    else {
                        MGUI_SetStamp(slot, mguiEditorBrushContent, GetMouseX(), GetMouseY(), 
                            mguiEditorBrushXFactor, mguiEditorBrushYFactor, mguiEditorBrushFont, mguiEditorBrushWrap);
                        mguiEditorStampCount++;
                        MGUI_Play(MGUI_EDITOR_SFX_STAMP_ADD);
                    }
                    MGUI_SetEditorMode(MGUI_EDITOR_MODE_SELECT);
                    break;
            }
            break;

        // Right click press
        case MGUI_EVENT_ALT_DOWN:
            switch(mguiEditorMode) {

                case MGUI_EDITOR_MODE_SELECT: 
                    if(areaId != MGUI_AREA_NULL) {
                        MGUI_Play(MGUI_EDITOR_SFX_STAMP_REMOVE);
                        MGUI_RemoveStamp(areaId);
                    }
                    break;

                case MGUI_EDITOR_MODE_MOVE:
                    MGUI_SetEditorMode(MGUI_EDITOR_MODE_SCALE);
                    break;
            }
            break;

        // Right click release
        case MGUI_EVENT_ALT_UP:
            switch(mguiEditorMode) {
                case MGUI_EDITOR_MODE_SCALE:
                    MGUI_SetEditorMode(MGUI_EDITOR_MODE_MOVE);
                    break;
            }
            break;
    }
}

script "MegaUI Build" (void) CLIENTSIDE {
    if(!mguiEditorIsRunning) {
        MGUI_EditorLog("You must be in the editor to generate code.");
        terminate;
    }

    str string = "\n
        //===================================//\n
        //          Mega UI ACS [START]      //\n
        //===================================//\n";
    for(int slot = 0; slot < mguiEditorStampCount; slot++) {

        int hudWidth = MGUI_FactorToHud(mguiEditorStampXFactor[slot], MGUI_HUD_WIDTH),
            hudHeight = MGUI_FactorToHud(mguiEditorStampYFactor[slot], MGUI_HUD_HEIGHT),
            x = MGUI_FactorToHud(mguiEditorStampX[slot], hudWidth),
            y = MGUI_FactorToHud(mguiEditorStampY[slot], hudHeight);

        if(MGUIEditor_IsText(slot)) {
            string = strParam(s:string, s:"\nShowText(",
                s:"MGUI_DRAWID+", d:slot, 
                s:", \"",   s:mguiEditorStampContent[slot], 
                s:"\", \"", s:mguiEditorStampFont[slot], 
                s:"\", ",   d:x,
                s:", ",     d:y,
                s:", ",     d:hudWidth,
                s:", ",     d:hudHeight,
                s:", ",     d:MGUI_FactorToHud(mguiEditorStampWrap[slot], hudWidth),
                s:", ",     s:(1.0 ? "1.0" : strParam(d:1.0)),
                s:");"
            );
        }
        else {
            string = strParam(s:string, s:"\nShow(",
                s:"MGUI_DRAWID+", d:slot, 
                s:", \"",   s:mguiEditorStampContent[slot], 
                s:"\", ",   d:x,
                s:", ",     d:y,
                s:", ",     d:hudWidth,
                s:", ",     d:hudHeight,
                s:", ",     s:(1.0 ? "1.0" : strParam(d:1.0)),
                s:");"
            );

        }
        
    }

    string = strParam(s:string, s:"\n\n
        //===================================//\n
        //       	 Mega UI ACS [END]        	//\n
        //===================================//\n");

    log(s:string);
    consoleCommand("toggleconsole");
}




script "voyons" (void) {
    ShowText(MGUI_DRAWID+0, "letters7", "SMALLFONT", 212, 84, 320, 240, 320, 1.0);
 "SMALLFONT", 83, 176, 320, 240, 206, 1.0);
}
