
// -------------------------------------------------------------------------------------------
//      Stamps
// -------------------------------------------------------------------------------------------

#DEFINE MGUI_EDITOR_STAMP_HOOK_ALPHA       0.4

int mguiEditorStampCount = 0;
str mguiEditorStampContent[MGUI_EDITOR_STAMP_MAX+1],
    mguiEditorStampFont[MGUI_EDITOR_STAMP_MAX+1];
int mguiEditorStampX[MGUI_EDITOR_STAMP_MAX+1],
    mguiEditorStampY[MGUI_EDITOR_STAMP_MAX+1],
    mguiEditorStampXFactor[MGUI_EDITOR_STAMP_MAX+1],
    mguiEditorStampYFactor[MGUI_EDITOR_STAMP_MAX+1],
    mguiEditorStampWrap[MGUI_EDITOR_STAMP_MAX+1],
    mguiEditorStampAlpha[MGUI_EDITOR_STAMP_MAX+1];

function int MGUIEditor_GetStampType(int slot) {            return (mguiEditorStampWrap[slot] == 0) ? MGUI_EDITOR_BRUSH_GRAPHIC : MGUI_EDITOR_BRUSH_TEXT; }
function int MGUIEditor_GetStampIdFromSlot(int slot) {      return (MGUI_EDITOR_STAMP_DRAWID_END - 1) - (slot<<1); }
function int MGUIEditor_GetSlotFromStampId(int stampId) {   return ((MGUI_EDITOR_STAMP_DRAWID_END - 1) - stampId)>>1; }
function void MGUIEditor_DrawStampHook(int stampId, bool isFocused) {
    int slot = MGUIEditor_GetSlotFromStampId(stampId);
    Show(stampId-1, "MEGAUI_6", (mguiEditorStampX[slot]*320)>>16, (mguiEditorStampY[slot]*240)>>16, 320, 240, isFocused ? 1.0 : MGUI_EDITOR_STAMP_HOOK_ALPHA);
}

function void MGUIEditor_SetStamp(int slot, str content, int x, int y, int xFactor, int yFactor, str font, int wrap, int alpha) {
    mguiEditorStampContent[slot] =      content;
    mguiEditorStampX[slot] =            x;
    mguiEditorStampY[slot] =            y;
    mguiEditorStampXFactor[slot] =      xFactor;
    mguiEditorStampYFactor[slot] =      yFactor;
    mguiEditorStampFont[slot] =         font;
    mguiEditorStampWrap[slot] =         wrap;
    mguiEditorStampAlpha[slot] =        alpha;

    int stampId = MGUIEditor_GetStampIdFromSlot(slot);

    int hudWidth = MGUIEditor_ToHud(xFactor, MGUI_HUD_WIDTH),
        hudHeight = MGUIEditor_ToHud(yFactor, MGUI_HUD_HEIGHT);

    if(MGUIEditor_GetStampType(slot)==MGUI_EDITOR_BRUSH_TEXT) 
        ShowText(   stampId, content, font,  (x*hudWidth)>>16, (y*hudHeight)>>16, hudWidth, hudHeight, MGUIEditor_ToHud(wrap, hudWidth), alpha);
    else
        Show(       stampId, content,        (x*hudWidth)>>16, (y*hudHeight)>>16, hudWidth, hudHeight, alpha);

    SetMouseArea(stampId, (x*320)>>16, (y*240)>>16, 16, 16, 320, 240);
    MGUIEditor_DrawStampHook(stampId, false);
}

function void MGUIEditor_DeleteStamp(int stampId) {
    for(int slotA = 0; slotA < mguiEditorStampCount; slotA++) {
        if(MGUIEditor_GetStampIdFromSlot(slotA) == stampId) {
            for(int slotB = slotA; slotB < mguiEditorStampCount; slotB++) {
                MGUIEditor_SetStamp(slotB, 
                    mguiEditorStampContent[slotB+1], 
                    mguiEditorStampX[slotB+1], 
                    mguiEditorStampY[slotB+1], 
                    mguiEditorStampXFactor[slotB+1], 
                    mguiEditorStampYFactor[slotB+1],
                    mguiEditorStampFont[slotB+1],
                    mguiEditorStampWrap[slotB+1],
                    mguiEditorStampAlpha[slotB+1]
                );
            }

            // Erase the last one
            stampId = MGUIEditor_GetStampIdFromSlot(mguiEditorStampCount-1);
            DeleteMouseArea(stampId);
            Hide(stampId);
            Hide(stampId-1); // Hook icon
            mguiEditorStampCount--;
            return;
        }
    }
}
