// -------------------------------------------------------------------------------------------
//     Dance dance revolution
// -------------------------------------------------------------------------------------------

/*  
        [ Dance dance revolution game ]

    > Mouse area ids are given #DEFINE names for easier management. They're either
        - The 4 grey arrows
            - Highlighted on mouse hover
            - React/consume the beat on click
        - The right menu items
            - Turn to big font on hover
            - Control game state on click
    > 3 songs
    > Use Draw() for the notes (since they change position every frame) ; and Show() for everything else
*/


// ================ Defs / data / consts ================ //

#DEFINE DDR_INPUT_COUNT     4 // 4 arrows
#DEFINE DDR_TRACK_COUNT     3
#DEFINE DDR_MAX_NOTES       256 // max beats / notes per track

#DEFINE DDR_NOTE_PERFECT_Y  139 // Grey arrow position
#DEFINE DDR_NOTE_START_Y    738 // Note spawn position

#DEFINE DDR_ARROW_WIDTH     984
#DEFINE DDR_ARROW_HEIGHT    738

// Track BPM / delay() between beats
#DEFINE DDR_BPM_117         9   // => 116.67 BPM
#DEFINE DDR_BPM_150         7

// Mouse area ids
#DEFINE AREAID_ARROWS               0                               // [0, DDR_INPUT_COUNT = 4[
#DEFINE AREAID_MENU_START           AREAID_ARROWS           +DDR_INPUT_COUNT
    #DEFINE AREAID_MENU_STOP        AREAID_MENU_START
    #DEFINE AREAID_MENU_TRACKS      AREAID_MENU_STOP        +1
    #DEFINE AREAID_MENU_METRONOM    AREAID_MENU_TRACKS      +DDR_TRACK_COUNT
    #DEFINE AREAID_MENU_EXIT        AREAID_MENU_METRONOM    +1
#DEFINE AREAID_MENU_END             AREAID_MENU_EXIT        +1

// HudMessageIds
#DEFINE DRAWID_DDR_TITLE            2000
#DEFINE DRAWID_DDR_JUDGMENT         DRAWID_DDR_TITLE +1
#DEFINE DRAWID_DDR_COMBO            DRAWID_DDR_JUDGMENT +1
#DEFINE DRAWID_DDR_ARROWS           DRAWID_DDR_COMBO+1
#DEFINE DRAWID_DDR_ARROW_HIGHLIGHT  DRAWID_DDR_ARROWS +DDR_INPUT_COUNT
#DEFINE DRAWID_DDR_MENU             DRAWID_DDR_ARROW_HIGHLIGHT +DDR_INPUT_COUNT
#DEFINE DRAWID_DDR_BG               DRAWID_DDR_MENU +(AREAID_MENU_END-AREAID_MENU_START)

// Grey arrow click bounce animation 
#DEFINE DDR_ARROW_ANIM_T    5  // Duration
int ddrPress[DDR_INPUT_COUNT]; // Duration status

// Grey arrows
int ddrArrowBasePic[DDR_INPUT_COUNT] = {        "MEGAUIG6", "MEGAUIG9", "MEGAUIG7", "MEGAUIG8" };

// Colored arrows
int ddrArrowBeatPic[3][DDR_INPUT_COUNT] = {
    { "MEGAUIGA", "MEGAUIGD", "MEGAUIGB", "MEGAUIGC" }, // 1/1 beat
    { "MEGAUIGM", "MEGAUIGQ", "MEGAUIGO", "MEGAUIGP" }, // 1/2 beat
    { "MEGAUIGN", "MEGAUIGT", "MEGAUIGR", "MEGAUIGS" }, // 1/4 beat
};




// ================ Track data  ================ //

// Music code
int ddrTrackCode[DDR_TRACK_COUNT] = {
   "MEGAUIM0", 
   "MEGAUIM1", 
   "MEGAUIM2",
};

// Track display name
int ddrTrackName[DDR_TRACK_COUNT] = {
   "Savaged Regime - Comix Zone ~ Episode 1 Page 2-1 (YM2612)",
   "Zero Wing - Gerbarra (Stage 8)",
   "Allanx - Overclocked (Forgotten Navi Theme)",
};

int ddrTrackBPM[DDR_TRACK_COUNT] = {
   DDR_BPM_117,
   DDR_BPM_150,
   DDR_BPM_150,
};

// Beatmap : 0 (None), 1 Left, 2 Down, 3 Up, 4 Right
int ddrTrackBeatmap[DDR_TRACK_COUNT][DDR_MAX_NOTES] = {
    // Track 1
    {
        1, 0, 3, 0,     1, 0, 3, 0,     4, 0, 3, 0,     2, 0, 3, 0, 
        1, 0, 3, 0,     1, 0, 3, 0,     4, 0, 3, 0,     2, 0, 3, 2, 
        1, 0, 2, 0,     3, 0, 4, 0,     4, 0, 3, 0,     2, 0, 2, 0, 
        3, 0, 4, 0,     3, 0, 2, 0,     3, 0, 4, 0,     3, 0, 3, 2, 

        1, 0, 4, 0,     1, 0, 4, 0,     3, 0, 2, 0,     1, 0, 1, 0, 
        2, 0, 4, 0,     3, 0, 4, 0,     4, 0, 2, 0,     1, 0, 3, 2, 
        1, 0, 2, 0,     3, 0, 4, 0,     4, 0, 3, 0,     2, 0, 2, 0, 
        3, 0, 4, 0,     3, 0, 2, 0,     3, 0, 4, 0,     3, 0, 3, 2, 

        1, 0, 4, 0,     1, 0, 4, 0,     3, 0, 2, 0,     1, 0, 1, 0, 
        2, 0, 4, 0,     3, 0, 4, 0,     4, 0, 2, 0,     1, 0, 3, 2, 
        1, 0, 3, 0,     4, 0, 0, 0,     2, 0, 4, 0,     3, 0, 0, 0, 
        3, 0, 2, 0,     4, 0, 4, 0,     1, 1, 4, 0,     1, 0, 4, 0, 

        2, 2, 4, 0,     2, 0, 4, 0,     1, 0, 3, 0,     4, 0, 0, 0,
        2, 0, 4, 0,     3, 0, 0, 0,     4, 0, 3, 0,     4, 0, 4, 4,
        4, 0, 2, 0,     3, 0, 1, 0,     1, 0, 2, 0,     3, 0, 4, 0, 
        1, 0, 3, 0,     2, 0, 4, 0,     4, 0, 3, 0,     2, 0, 1, 0, 
    },

    // Track 2
    {
        2, 2, 0, 0,     0, 0, 0, 0,     3, 3, 0, 0,     0, 0, 0, 0,
        4, 4, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0,
        3, 0, 1, 0,     2, 0, 3, 2,     4, 0, 1, 0,     3, 0, 2, 3, 
        1, 0, 3, 0,     3, 0, 2, 3,     1, 0, 4, 0,     2, 0, 3, 2, 

        3, 0, 1, 0,     2, 0, 3, 2,     4, 0, 1, 0,     3, 0, 2, 3, 
        1, 0, 3, 0,     3, 0, 2, 3,     1, 2, 3, 4,     4, 3, 2, 1, 
        2, 0, 3, 0,     1, 0, 3, 4,     4, 0, 0, 0,     3, 0, 1, 0,
        3, 0, 2, 0,     4, 0, 2, 0,     4, 0, 3, 1,     2, 0, 1, 0,

        2, 0, 3, 0,     1, 0, 3, 4,     4, 0, 0, 0,     3, 0, 1, 0,
        3, 0, 2, 0,     4, 0, 2, 0,     4, 0, 3, 2,     1, 2, 3, 2,
        1, 0, 4, 0,     1, 1, 3, 3,     4, 0, 2, 0,     4, 3, 2, 1,
        2, 0, 1, 0,     3, 0, 2, 0,     4, 4, 3, 3,     4, 0, 2, 1, 

        1, 0, 3, 0,     1, 1, 3, 3,     4, 0, 2, 0,     4, 4, 2, 2,
        3, 0, 2, 0,     3, 1, 2, 0,     3, 0, 4, 0,     2, 0, 3, 0,
        2, 1, 2, 0,     3, 2, 3, 0,     1, 0, 4, 0,     3, 2, 1, 4, 
        2, 0, 4, 0,     1, 0, 3, 0,     2, 0, 3, 0,     1, 1, 4, 0
    },

    // Track 3
    {
        3, 0, 0, 0,     0, 0, 0, 0,     2, 0, 0, 0,     0, 0, 0, 0,
        4, 0, 0, 0,     0, 0, 0, 0,     1, 0, 0, 0,     0, 0, 0, 0,
        4, 0, 2, 0,     4, 0, 2, 0,     4, 0, 2, 0,     4, 3, 2, 1,
        1, 0, 3, 0,     1, 0, 3, 0,     1, 3, 2, 4,     3, 2, 1, 1,

        2, 3, 4, 3,     2, 1, 4, 0,     2, 3, 4, 3,     2, 1, 4, 0,
        3, 2, 1, 2,     3, 4, 2, 0,     3, 2, 1, 2,     3, 4, 2, 0,     
        2, 3, 4, 3,     2, 1, 4, 0,     2, 3, 4, 3,     2, 1, 4, 0,
        3, 2, 1, 2,     3, 4, 2, 0,     3, 2, 1, 2,     3, 4, 2, 3,

        1, 2, 3, 1,     1, 2, 3, 0,     1, 2, 3, 1,     1, 2, 3, 0,
        4, 3, 2, 4,     4, 3, 2, 0,     4, 3, 2, 4,     4, 3, 2, 0,     
        1, 2, 3, 1,     1, 2, 3, 0,     1, 2, 3, 1,     1, 2, 3, 0,
        4, 3, 2, 4,     4, 3, 2, 0,     4, 3, 2, 4,     4, 3, 2, 3,

        1, 2, 3, 4,     4, 3, 2, 1,     4, 3, 2, 1,     1, 2, 3, 4,
        1, 3, 2, 4,     1, 3, 2, 4,     4, 2, 4, 1,     4, 2, 3, 1,
        1, 2, 3, 4,     4, 3, 2, 1,     4, 3, 2, 1,     1, 2, 3, 4,
        1, 3, 2, 4,     1, 3, 2, 4,     4, 2, 4, 1,     4, 2, 3, 1,
    },
};




// ================ Script start ================ //

bool useMetronom = false;
// Currently playing track, -1 if none
int ddrTrack = -1;

// Judgment == The "Perfect/Great" message on hitting a note
int ddrJudgment;            
int ddrJudgmentDuration;
// Unmissed notes combo
int ddrCombo;

script "MegaUI DDR" (void) CLIENTSIDE {

	// Start the mouse menu / receive callback events in given script
    if(!StartMouseMenu("MegaUI DDR Callback"))
        terminate;

	SetPlayerProperty(0, true, PROP_TOTALLYFROZEN);

	MGUIGames_DebugMessage(true);

    // Fade background
    for(int i = 0; i <= 20; i++) {
        Show(DRAWID_DDR_BG, "MEGAUIGF", 24, 18, 50, 37, FixedMul(FixedDiv(i<<16, 20.0), 0.7));
        delay(1);
    }

    // Grey arrow area setup
    for(i = 0; i < DDR_INPUT_COUNT; i++)
        SetMouseArea(i, GetArrowX(i), 138, 984, 738, 104, 104);

    // Right menu display / area setup
    for(int areaId = AREAID_MENU_START; areaId < AREAID_MENU_END; areaId++) {
        UpdateDDRMenu(areaId, false);
        SetMouseArea(areaId, 245, GetDDRMenuY(areaId), 320, 170, 66, 16);
    }

    for(i = 0; i < DDR_INPUT_COUNT; i++) 
        ddrPress[i] = 0;
    SetDDRTrack(-1);
    while(true) {
        // Update grey arrow bounce animation
        for(i = 0; i < DDR_INPUT_COUNT; i++) {
            if(ddrPress[i] > -1) {
                int scale = 1.0 + FixedMul(FixedDiv(ddrPress[i]<<16, DDR_ARROW_ANIM_T<<16), 0.5);
                Show(DRAWID_DDR_ARROWS+i, ddrArrowBasePic[i], 
                    FixedDiv(GetArrowX(i)<<16, scale)>>16, 
                    FixedDiv(DDR_NOTE_PERFECT_Y<<16, scale)>>16, 
                    FixedDiv(DDR_ARROW_WIDTH<<16, scale)>>16, 
                    FixedDiv(DDR_ARROW_HEIGHT<<16, scale)>>16, 
                    1.0);
                ddrPress[i]--;
            }
        }

        // Update judgment display
        if(ddrJudgmentDuration) {
            ddrJudgmentDuration--;
            if(!ddrJudgmentDuration) {
                Hide(DRAWID_DDR_JUDGMENT);
                Hide(DRAWID_DDR_COMBO);
            }
        }
        delay(1);
    }
}

// Arrow's center X position
function int GetArrowX(int index) { 
    return 112+107*index; 
}

// Right menu's item Y position
function int GetDDRMenuY(int areaId) { 
    return 57+((areaId-AREAID_MENU_START)*16); 
}

// Refresh the rendering of an item on the right menu
function void UpdateDDRMenu(int areaId, int isFocused) {
    str text;
    switch(areaId) {
        case AREAID_MENU_STOP:      text = "\c[d9]STOP"; break;
        case AREAID_MENU_TRACKS+0:  text = "\c[e2][ NORMAL ]"; break;
        case AREAID_MENU_TRACKS+1:  text = "\c[e3][ HARD ]"; break;
        case AREAID_MENU_TRACKS+2:  text = "\c[b5][ LUNATIC ]"; break;
        case AREAID_MENU_METRONOM:  text = StrParam(s:"\c[e0]METRONOM ", s:(useMetronom ? "\cdON" : "\ccOFF")); break;
        case AREAID_MENU_EXIT:      text = "\c[45]Exit game"; break;
    }
    int index = (areaId-AREAID_MENU_START);
    if((areaId==AREAID_MENU_STOP) && (ddrTrack==-1)) // Stop
        Hide(DRAWID_DDR_MENU+index);
    else
        ShowText(DRAWID_DDR_MENU+index, text, (isFocused ? "BIGFONT" : "SMALLFONT"), 244, GetDDRMenuY(areaId), 320, 170, 0, 1.0, 0);
}

function void SetDDRTrack(int track) {
    // Play track ; on
    if(track != -1) {
        ShowText(DRAWID_DDR_TITLE, StrParam(s:"\cdNow playing:\n\ca", s:ddrTrackName[track]), "smallfont", 246, 26, 320, 240, 132, 1.0, MGUI_CENTER|MGUI_TYPEON|0.04); 
        // Start game script if we weren't playing a track already
        if(ddrTrack == -1)
            ACS_NamedExecuteWithResult("MegaUI DDR Play");
        ddrTrack = track;
    }
    // No track ; off
    else {
        ddrTrack = -1;
        ShowText(DRAWID_DDR_TITLE, "Pick a track below", "bigfont", 246, 26, 320, 240, 132, 1.0, MGUI_CENTER|MGUI_TYPEON|0.04); 
        SetMusic("*");
    }
    UpdateDDRMenu(AREAID_MENU_STOP, false);
}




// ------------------------------------------------------------------------------------------------------
//        In-game
// ------------------------------------------------------------------------------------------------------

#DEFINE DDR_MAX_BUFFER_NOTES    16

// Judgment accuracy in tics
#DEFINE DDR_ACCURACY_PERFECT    1
#DEFINE DDR_ACCURACY_GREAT      DDR_ACCURACY_PERFECT+1
#DEFINE DDR_ACCURACY_GOOD       DDR_ACCURACY_GREAT+1
#DEFINE DDR_ACCURACY_MISS       DDR_ACCURACY_GOOD+1

#DEFINE DDR_JUDGMENT_BASE_DURATION   12

// How long from spawn until considered missed note duration
#DEFINE DDR_NOTE_DURATION       35 +DDR_ACCURACY_MISS 

// Syncs the notes better idk
#DEFINE DDR_SYNC_FIX            5

// Current beat of the track / track progress
int ddrBeat; 

// Buffer is the current all notes visible on screen
int ddrBufferCount;
int ddrNoteBuffer[DDR_MAX_BUFFER_NOTES+1];  // Note data (left/down/up/right)
int ddrTimerBuffer[DDR_MAX_BUFFER_NOTES+1]; // Time before they go "miss"
int ddrBeatBuffer[DDR_MAX_BUFFER_NOTES+1];  // Whether it's a 1/1 (red), 1/2 (blue) or 1/4 (yellow) beat


// Some computed constants for note position rendering
int DDR_PERFECT_TO_MISS_RATIO;
int DDR_TOTAL_Y_DISTANCE;


script "MegaUI DDR Play" (void) CLIENTSIDE {
    DDR_PERFECT_TO_MISS_RATIO = FixedDiv(DDR_NOTE_DURATION<<16, (DDR_NOTE_DURATION-DDR_ACCURACY_MISS)<<16);
    DDR_TOTAL_Y_DISTANCE = FixedMul((DDR_NOTE_START_Y-DDR_NOTE_PERFECT_Y)<<16, DDR_PERFECT_TO_MISS_RATIO);

    // The track for this game session
    int sessionTrack = ddrTrack;

    // Reset / init
    for(int i = 0; i < DDR_MAX_BUFFER_NOTES+1; i++) 
        ddrNoteBuffer[i] = -1;
    ddrBufferCount = 0;
    ddrBeat = 0;
    ddrCombo = 0;
    ddrJudgmentDuration = 0;
    int rhythm = (ddrTrackBPM[sessionTrack] >= 1 ? ddrTrackBPM[sessionTrack] : 1);

    // Intro (~1s wait until first note reaches grey arrow)
    SetMusic("");
    int t = 0;
    int intro = DDR_NOTE_DURATION-DDR_ACCURACY_MISS;
    while(true) {
        t = DDRPlay(t, rhythm, sessionTrack, true);
        if(t == -1)
            terminate;
        intro--;
        delay(1);
        if(!intro)
            break;
    }

    // First beat ~ music start
    SetMusic(ddrTrackCode[sessionTrack]);
    while(true) {
        t = DDRPlay(t, rhythm, sessionTrack, false);
        if(t == -1)
            terminate;
        delay(1);
    }
}

// Progress the track 1 tic and update game status
function int DDRPlay(int t, int rhythm, int sessionTrack, int playMetronom) {
    // Complete the game once all notes were spawned and popped from buffer
    if((ddrBeat > DDR_MAX_NOTES) && (ddrNoteBuffer[0]==-1))
        SetDDRTrack(-1);

    if(sessionTrack != ddrTrack) {
        // Stopped the track : stop the current game session
        if(ddrTrack == -1)
            return -1;

        // Queried another track : stop the current game session
        else {                  
            ACS_NamedExecuteWithResult("MegaUI DDR Play"); 
            return -1; 
        }
    }

    // Push a new beat to buffer every [rhythm] tics
    bool isBeat = !t;
    if(isBeat) {
        PushDDRBeat();
        t = rhythm-1;
    }
    else
        t--;

    // Update note rendering / pop missed notes from buffer
    CalcDDRBeats();
    
    if((playMetronom | useMetronom) && isBeat)
        LocalAmbientSound("MEGAUIG7", 90);
    return t;
}

// Push a new note to the buffer
function void PushDDRBeat(void) {
    int note = ddrTrackBeatmap[ddrTrack][ddrBeat];
    ddrBeat++;
    if(!note) // no note at current beat position
        return;
    ddrNoteBuffer[ddrBufferCount] = note-1;
    ddrTimerBuffer[ddrBufferCount] = Timer()+DDR_NOTE_DURATION+DDR_SYNC_FIX;
    int color = (ddrBeat-1) & 0x3;
    ddrBeatBuffer[ddrBufferCount] = !color ? 0 : (color&0x1 ? 2 : 1);
    ddrBufferCount++;
}

function void CalcDDRBeats(void) {
    // No note in buffer
    if(ddrNoteBuffer[0] == -1)
        return;
    int t = Timer();

    // Remove first note if its hit windows elapsed
    if((ddrTimerBuffer[0]-t) <= 0)
        ShiftDDRBeat(DDR_ACCURACY_MISS);
    
    // Note display rendering
    for(int i = 0; i < ddrBufferCount; i++) {
        int normalizedDistance = FixedDiv((ddrTimerBuffer[i]-t)<<16, DDR_NOTE_DURATION<<16);
        int yPos = DDR_NOTE_START_Y - (FixedMul(DDR_TOTAL_Y_DISTANCE, 1.0-normalizedDistance)>>16);
        int note = ddrNoteBuffer[i];
        Draw(ddrArrowBeatPic[ddrBeatBuffer[i]][note], GetArrowX(note), yPos, 984, 738, 1.0);
    }
}

// Pop the first note of the buffer, and shift all others
function void ShiftDDRBeat(int accuracy) {
    for(int i = 0; i < ddrBufferCount; i++) {
        ddrNoteBuffer[i] = ddrNoteBuffer[i+1];
        ddrTimerBuffer[i] = ddrTimerBuffer[i+1];
        ddrBeatBuffer[i] = ddrBeatBuffer[i+1];
    }
    ddrBufferCount--;
    ddrCombo = (accuracy == DDR_ACCURACY_MISS) ? 0 : ddrCombo+1;

    // Update judgment display
    switch(accuracy) {
        case DDR_ACCURACY_PERFECT: ddrJudgment = "MEGAUIGG"; break;
        case DDR_ACCURACY_GREAT: ddrJudgment = "MEGAUIGH"; break;
        case DDR_ACCURACY_GOOD: ddrJudgment = "MEGAUIGI"; break;
        case DDR_ACCURACY_MISS: ddrJudgment = "MEGAUIGJ"; break;
    }
    Show(DRAWID_DDR_JUDGMENT, ddrJudgment, 178, 259, 619, 464, 1.0);
    ddrJudgmentDuration = DDR_JUDGMENT_BASE_DURATION;
    if(ddrCombo > 2)
        ShowText(DRAWID_DDR_COMBO, StrParam(d:ddrCombo, s:" combo"), "bigfont", 117, 199, 412, 309, 0, 1.0, 0);
    else
        Hide(DRAWID_DDR_COMBO);
}



// ------------------------------------------------------------------------------------------------------
//        Mouse area events
// ------------------------------------------------------------------------------------------------------

script "MegaUI DDR Callback" (int e, int areaId) {
    switch(e) {
        
		// On hover area
		case MGUI_EVENT_ENTER:

            // Right menu enter
            if(areaId >= AREAID_MENU_START)
                UpdateDDRMenu(areaId, true);

            // Grey arrow enter
            else 
                SetArrowHighlight(areaId, true);

			break;

		// On exit area
		case MGUI_EVENT_EXIT:

            // Right menu exit
            if(areaId >= AREAID_MENU_START) 
                UpdateDDRMenu(areaId, false);

            // Grey arrow exit
            else
                SetArrowHighlight(areaId, false);

			break;

        // On fire press
        case MGUI_EVENT_DOWN:

            // If clicked into [no area], do nothing
            if(areaId == MGUI_NULL_AREA) 
                terminate;

            // Right menu click
            if(areaId >= AREAID_MENU_START)
                OnDDRMenuClick(areaId);

            // Grey arrow click
            else 
                OnArrowClick(areaId);
            break;

		// On altfire press
		case MGUI_EVENT_ALT_DOWN:
			MGUI_SetDebug(true);
			break;

		// On altfire release
		case MGUI_EVENT_ALT_UP:
			MGUI_SetDebug(false);
			break;
        
    }
}

function void OnDDRMenuClick(int areaId) {

    // Stop button
    if(areaId == AREAID_MENU_STOP) {
        if(ddrTrack==-1) // Already stopped, ignore the click
            return;
        SetDDRTrack(-1);
    }

    // Metronom button
    else if(areaId == AREAID_MENU_METRONOM) {
        useMetronom = !useMetronom;
        LocalAmbientSound("MEGAUIG0", 127);
        UpdateDDRMenu(AREAID_MENU_METRONOM, true);
    }
    
    // Exit game nutton
    else if(areaId == AREAID_MENU_EXIT) {
        ddrTrack = -1;
        SetMusic("*");
        // Hide every hudMessageIds of DDR
        HideRange(DRAWID_DDR_TITLE, (DRAWID_DDR_BG+1-DRAWID_DDR_TITLE));
        LocalAmbientSound("MEGAUIG2", 127);
        EndMouseMenu();
        SetPlayerProperty(0, false, PROP_TOTALLYFROZEN);
        MGUIGames_DebugMessage(false);
    }

    // Any track's button
    else
        SetDDRTrack(areaId-AREAID_MENU_TRACKS);
}

function void OnArrowClick(int index) {
    ddrPress[index] = DDR_ARROW_ANIM_T; // Refresh bouncy animation
    if(ddrTrack == -1) // Not playing a track
        return;
    int note = ddrNoteBuffer[0];
    if(note == -1) // No note buffered yet
        return;
    else if(index == note) { // If matches clicked arrow's type (left down etc), resolve timing
        int timing = (ddrTimerBuffer[0]-Timer())-DDR_ACCURACY_MISS;
        if(timing < 0) timing = -timing;
        if(timing <= DDR_ACCURACY_PERFECT)      ShiftDDRBeat(DDR_ACCURACY_PERFECT);
        else if(timing <= DDR_ACCURACY_GREAT)   ShiftDDRBeat(DDR_ACCURACY_GREAT);
        else if(timing <= DDR_ACCURACY_GOOD)    ShiftDDRBeat(DDR_ACCURACY_GOOD);
    }
}

// Display grey arrow background highlight on hover
function void SetArrowHighlight(int index, bool state) {
    if(state)
        Show(DRAWID_DDR_ARROW_HIGHLIGHT+index, "MEGAUIGE", GetArrowX(index), 139, 984, 738, 0.4);
    else
        Hide(DRAWID_DDR_ARROW_HIGHLIGHT+index);
}
