
// -------------------------------------------------------------------------------------------
//     Definitions 
// -------------------------------------------------------------------------------------------

#DEFINE MGUI_EDITOR_STAMP_MAX           256
#DEFINE MGUI_EDITOR_HELP_CVAR           "megaui_help"
#DEFINE MGUI_EDITOR_TEXT_ON             "\c[80]ON\c-"
#DEFINE MGUI_EDITOR_TEXT_OFF            "\c[p3]OFF\c-"

// DrawIds
#DEFINE MGUI_EDITOR_STAMP_DRAWID        MGUI_DEBUG_AREA_DRAWID_END
#DEFINE MGUI_EDITOR_STAMP_DRAWID_END    MGUI_EDITOR_STAMP_DRAWID + (MGUI_EDITOR_STAMP_MAX * 2) // 1 stamp id + 1 stamp's "..." hook icon id
#DEFINE MGUI_DRAWID                     MGUI_EDITOR_STAMP_DRAWID_END
#DEFINE MGUI_EDITOR_BACKGROUND_DRAWID   0x7FFFFFA


// Sounds
#DEFINE MGUI_EDITOR_SFX_NO              "misc/wanaan"
#DEFINE MGUI_EDITOR_SFX_STAMP_ADD       "misc/mercuryconveyorswitch"
#DEFINE MGUI_EDITOR_SFX_STAMP_REMOVE    "misc/eclipsedarkshot"
#DEFINE MGUI_EDITOR_SFX_TOGGLE          "misc/cursorq"
#DEFINE MGUI_EDITOR_SFX_RESET           "misc/fakereloadshort"
#DEFINE MGUI_EDITOR_SFX_STAMP_EQUIP     "misc/venusdrip"
#DEFINE MGUI_EDITOR_SFX_MODE            "misc/terraclick"

// Modes
#DEFINE MGUI_EDITOR_MODE_SELECT             0
#DEFINE MGUI_EDITOR_MODE_BRUSH_MOVE         1
#DEFINE MGUI_EDITOR_MODE_BRUSH_HUD          2
#DEFINE MGUI_EDITOR_MODE_BRUSH_JUMP         3
#DEFINE MGUI_EDITOR_MODE_BRUSH_CROUCH       4


// Events?
#DEFINE MGUI_EDITOR_MOUSE_DELTA     0.002
#DEFINE MGUI_EDITOR_SCALE_DELTA     0.003125
#DEFINE MGUI_EDITOR_WRAP_DELTA      0.003125
#DEFINE MGUI_EDITOR_ALPHA_DELTA     0.01
#DEFINE MGUI_EDITOR_HOLD_DURACTION  10

// Stamp types
#DEFINE MGUI_EDITOR_STAMP_GRAPHIC           0
#DEFINE MGUI_EDITOR_STAMP_TEXT              1
#DEFINE MGUI_EDITOR_STAMP_MOUSE_AREA        2