
// -------------------------------------------------------------------------------------------
//      Editor
// -------------------------------------------------------------------------------------------
// General state
bool    mguiEditorIsRunning;
int     mguiEditorMode;
str     mguiBannerText;
int     mguiBannerTimer;

// Currently held stamp's status
int     mguiEditorMouseType,
        mguiEditorMouseContent,
        mguiEditorMouseFont,
        mguiEditorMouseXFactor,
        mguiEditorMouseYFactor,
        mguiEditorMouseWrap,
        mguiEditorMouseAlpha,
        mguiEditorMouseIsUniformScale;

script "MegaUI Editor" (void) CLIENTSIDE {
    if(!StartMouseMenu("MegaUI Editor Event"))
        terminate;
    mguiEditorIsRunning = true;
    MGUIEditor_SetDefaultMouseBrush();
    SetPlayerProperty(0, 1, PROP_TOTALLYFROZEN);
    MGUIEditor_SetMode(MGUI_EDITOR_MODE_SELECT, true);
    int x, y, hudWidth, hudHeight;

    for(x = 0; x <= 27; x++) {
        Show(MGUI_EDITOR_BACKGROUND_DRAWID, "MEGAUI_9", 55, 55, 110, 110, FixedMul(FixedDiv(x<<16, 27.0), 0.8));
        delay(1);
    }
    log(l:"MGUI_EDITOR_OPEN");

    if(FixedDiv(GetScreenHeight()<<16, GetScreenWidth()<<16) != 0.75) {
        log(s:"\n\c[c5][ WARNING ] \c[r5]Your game resolution (\c[j5]", d:GetScreenWidth(), s:"x", d:GetScreenHeight(), 
            s:"\c[r5]) ratio is not 4:3 (800x600, 1024x768, etc).\n\c[r5]Please design your UI on 4:3 resolution to avoid ",
            s:"some out of screen issues for 4:3 players");
    }

    // Main thread
    while(true) {

        MGUIEditor_CheckInput();

        // Banner info
        if(mguiBannerTimer) {
            DrawText(mguiBannerText, "SMALLFONT", 150, 25, 300, 126, 240, MGUI_Min((mguiBannerTimer<<16)/10, 1.0));
            mguiBannerTimer--;
        }

        // Help
        if(GetUserCVar(PlayerNumber(), MGUI_EDITOR_HELP_CVAR)) {
            str stringBuilder;
            switch(mguiEditorMode) {

                case MGUI_EDITOR_MODE_SELECT:           
                    stringBuilder = "MGUI_EDITOR_SELECT"; 
                    break;

                case MGUI_EDITOR_MODE_BRUSH_MOVE:
                    switch(mguiEditorMouseType) {
                        case MGUI_EDITOR_STAMP_GRAPHIC:     stringBuilder = "MGUI_EDITOR_STAMP_GRAPHIC"; break;
                        case MGUI_EDITOR_STAMP_TEXT:        stringBuilder = "MGUI_EDITOR_STAMP_TEXT"; break;
                        case MGUI_EDITOR_STAMP_MOUSE_AREA:  stringBuilder = "MGUI_EDITOR_STAMP_MOUSE_AREA"; break;
                    }
                    break;

                case MGUI_EDITOR_MODE_BRUSH_HUD:            
                    stringBuilder = "MGUI_EDITOR_SCALE"; 
                    break;

                case MGUI_EDITOR_MODE_BRUSH_JUMP:
                    if(mguiEditorMouseType==MGUI_EDITOR_STAMP_MOUSE_AREA)   stringBuilder = "MGUI_EDITOR_SIZE";
                    else                                                    stringBuilder = "MGUI_EDITOR_ALPHA";
                    break;

                case MGUI_EDITOR_MODE_BRUSH_CROUCH:       
                    stringBuilder = "MGUI_EDITOR_WRAP"; 
                    break;
            }
            DrawText(strParam(l:stringBuilder), "smallfont", 77, 210, 674, 314, 148, 1.0);
        }

        // Stamp modes
        if(mguiEditorMode != MGUI_EDITOR_MODE_SELECT) {
            hudWidth = MGUIEditor_ToHud(mguiEditorMouseXFactor, MGUI_HUD_WIDTH), 
            hudHeight = MGUIEditor_ToHud(mguiEditorMouseYFactor, MGUI_HUD_HEIGHT),
            x = (GetMouseX()*hudWidth)>>16,
            y = (GetMouseY()*hudHeight)>>16;

            stringBuilder = "\c[y5]";
            switch(mguiEditorMouseType) {
                case MGUI_EDITOR_STAMP_GRAPHIC:     stringBuilder = strParam(s:stringBuilder, s:StrLeft(mguiEditorMouseContent, 8)); break;
                case MGUI_EDITOR_STAMP_TEXT:        stringBuilder = strParam(s:stringBuilder, s:"[TEXT]"); break;
                case MGUI_EDITOR_STAMP_MOUSE_AREA:  stringBuilder = strParam(s:stringBuilder, s:"{AREA}"); break;
            }

            stringBuilder = strParam(s:stringBuilder, s:"\n",
                s:"\c[j5]Pos \cj[", d:x, s:", ", d:y, s:"]\n", 
                s:"\c[o7]Hud \cj<", d:hudWidth, s:", ", d:hudHeight, s:">\n");
            if((mguiEditorMouseType==MGUI_EDITOR_STAMP_GRAPHIC) | (mguiEditorMouseType==MGUI_EDITOR_STAMP_TEXT)) {
                stringBuilder = strParam(s:stringBuilder, s:"\c[f2]Alpha \cj", d:(mguiEditorMouseAlpha*100)>>16, s:"%");
                if(mguiEditorMouseType==MGUI_EDITOR_STAMP_TEXT) {
                    int wrap = MGUIEditor_ToHud(mguiEditorMouseWrap, hudWidth);
                    stringBuilder = strParam(s:stringBuilder, s:"\n\c[05]Wrap \cj", d:wrap);
                }
            }
            // Mouse area
            else
                stringBuilder = strParam(s:stringBuilder, s:"\c[f2]Size \cj");
                    
            // Draw Inspector
            DrawText(stringBuilder, "smallfont", 444, 196, 502, 223, 502, 0.85);

            // Draw the stamp on mouse
            switch(mguiEditorMouseType) {

                case MGUI_EDITOR_STAMP_TEXT:
                    DrawText(mguiEditorMouseContent, mguiEditorMouseFont, x, y, hudWidth, hudHeight, wrap, mguiEditorMouseAlpha);
                    break;

                case MGUI_EDITOR_STAMP_GRAPHIC:
                    Draw(mguiEditorMouseContent, x, y, hudWidth, hudHeight, mguiEditorMouseAlpha);
                    break;

                case MGUI_EDITOR_STAMP_MOUSE_AREA:
                    break;
            }

        }
        delay(1);
    }
    SetPlayerProperty(0, 0, PROP_TOTALLYFROZEN);
    mguiEditorIsRunning = false;
    EndMouseMenu();
}

script "MegaUI Help" (void) { 
    int player = PlayerNumber();
    SetUserCVar(player, MGUI_EDITOR_HELP_CVAR, !GetUserCVar(player, MGUI_EDITOR_HELP_CVAR));
    MGUIEditor_ShowBanner(strParam(s:"Help menu ", s:GetUserCVar(player, MGUI_EDITOR_HELP_CVAR) ? MGUI_EDITOR_TEXT_ON : MGUI_EDITOR_TEXT_OFF));
    MGUIEditor_Play(MGUI_EDITOR_SFX_TOGGLE);
}

function void MGUIEditor_SetMode(int mode, bool isSilent) {
    mguiEditorMode = mode;
    switch(mode) {
        case MGUI_EDITOR_MODE_SELECT:
            SetMouseCursor("MEGAUI_3"); SetMouseOffset(6, 8); SetMouseSpeed(1.0); 
            break;

        case MGUI_EDITOR_MODE_BRUSH_MOVE:
            SetMouseCursor("MEGAUI_4"); SetMouseOffset(0, 0); SetMouseSpeed(1.0); 
            break;

        case MGUI_EDITOR_MODE_BRUSH_HUD:
            SetMouseCursor("MEGAUI_5"); SetMouseOffset(0, 0); SetMouseSpeed(0.0); 
            break;

        // Alpha (graphic/text) ; Size (mouse area)
        case MGUI_EDITOR_MODE_BRUSH_JUMP:
            SetMouseOffset(0, 0);
            SetMouseSpeed(0.0);
            SetMouseCursor(mguiEditorMouseType==MGUI_EDITOR_STAMP_MOUSE_AREA ? "MEGAUI_B" : "MEGAUI_8");   
            break;

        // Wrap (text)
        case MGUI_EDITOR_MODE_BRUSH_CROUCH:
            SetMouseCursor("MEGAUI_7"); SetMouseOffset(0, 0); SetMouseSpeed(0.0); 
            break;
    }
    if(isSilent)
        return;
    str stringBuilder;
    if(mode==MGUI_EDITOR_MODE_SELECT)
        stringBuilder = "Selection";
    else {
        switch(mguiEditorMouseType) {
            case MGUI_EDITOR_STAMP_TEXT:        stringBuilder = "text"; break;
            case MGUI_EDITOR_STAMP_GRAPHIC:     stringBuilder = "graphic"; break;
            case MGUI_EDITOR_STAMP_MOUSE_AREA:  stringBuilder = "mouse area"; break;
        }
        stringBuilder = StrParam(s:"Brush [", s:"\c[77]", s:stringBuilder, s:"\c[p7]", s:"]");
    }
    MGUIEditor_Play(MGUI_EDITOR_SFX_MODE);
    MGUIEditor_ShowBanner(stringBuilder);
}

function void MGUIEditor_SetMouseBrush(int type, str content, str font, int xFactor, int yFactor, int wrap, int alpha) {
    mguiEditorMouseType = type;
    mguiEditorMouseContent = content;
    mguiEditorMouseFont = font;
    mguiEditorMouseXFactor = xFactor;
    mguiEditorMouseYFactor = yFactor;
    mguiEditorMouseWrap = wrap;
    mguiEditorMouseAlpha = alpha;
}

function void MGUIEditor_SetDefaultMouseBrush(void) {
    MGUIEditor_SetMouseBrush(mguiEditorMouseType, mguiEditorMouseContent, "SMALLFONT", 1.0, 1.0, 1.0, 1.0);
    mguiEditorMouseIsUniformScale = true;
}

function void MGUIEditor_ShowBanner(str text) {
    mguiBannerTimer = 18+((StrLen(text)*5)/4);
    mguiBannerText = strParam(s:"\c[p7]", s:text);
}

