
// -------------------------------------------------------------------------------------------
//     ACS Generator 
// -------------------------------------------------------------------------------------------

// https://cleantextkit.com/remove-timestamps/


script "MegaUI Build" (void) CLIENTSIDE {
    if(!mguiEditorIsRunning) {
        MGUIEditor_Log("You must be in the editor to generate code.");
        terminate;
    }
    str stringBuilder = "\n
        //===================================//\n
        //          Mega UI ACS [START]      //\n
        //===================================//\n";

    //////////////////////////////
    //     Data parsing         //
    //////////////////////////////

    for(int slot = 0; slot < mguiEditorStampCount; slot++) {

        int hudWidth = MGUIEditor_ToHud(mguiEditorStampXFactor[slot], MGUI_HUD_WIDTH),
            hudHeight = MGUIEditor_ToHud(mguiEditorStampYFactor[slot], MGUI_HUD_HEIGHT),
            x = MGUIEditor_ToHud(mguiEditorStampX[slot], hudWidth),
            y = MGUIEditor_ToHud(mguiEditorStampY[slot], hudHeight);
        str alpha = mguiEditorStampAlpha[slot] == 1.0 ? "1.0" : strParam(f:mguiEditorStampAlpha[slot]);


        switch(mguiEditorStampType[slot]) {

            case MGUI_EDITOR_STAMP_TEXT:
                stringBuilder = strParam(s:stringBuilder, s:"\nShowText(",
                    s:"MGUI_DRAWID+", d:slot, 
                    s:", \"",   s:mguiEditorStampContent[slot], 
                    s:"\", \"", s:mguiEditorStampFont[slot], 
                    s:"\", ",   d:x,
                    s:", ",     d:y,
                    s:", ",     d:hudWidth,
                    s:", ",     d:hudHeight,
                    s:", ",     d:MGUIEditor_ToHud(mguiEditorStampWrap[slot], hudWidth),
                    s:", ",     s:alpha,
                    s:");"
                );
                break;

            case MGUI_EDITOR_STAMP_GRAPHIC:
                stringBuilder = strParam(s:stringBuilder, s:"\nShow(",
                    s:"MGUI_DRAWID+", d:slot, 
                    s:", \"",   s:mguiEditorStampContent[slot], 
                    s:"\", ",   d:x,
                    s:", ",     d:y,
                    s:", ",     d:hudWidth,
                    s:", ",     d:hudHeight,
                    s:", ",     s:alpha,
                    s:");"
                );
                break;

            case MGUI_EDITOR_STAMP_MOUSE_AREA:
                break;
        }
    }

    stringBuilder = strParam(s:stringBuilder, s:"\n\n
        //===================================//\n
        //       	 Mega UI ACS [END]        	//\n
        //===================================//\n");

    Log(s:stringBuilder);
    ConsoleCommand("toggleconsole");
}


