
// -------------------------------------------------------------------------------------------
//      Stamps
// -------------------------------------------------------------------------------------------

#DEFINE MGUI_EDITOR_HOOK_FOCUSED            0
#DEFINE MGUI_EDITOR_HOOK_IDLE               1


int mguiEditorStampCount = 0,
    mguiEditorStampType[MGUI_EDITOR_STAMP_MAX+1],       // Graphic/Text/Mouse area
    mguiEditorStampContent[MGUI_EDITOR_STAMP_MAX+1],    // Data (only for graphic/text)
    mguiEditorStampFont[MGUI_EDITOR_STAMP_MAX+1],       // Font (only for text)
    mguiEditorStampX[MGUI_EDITOR_STAMP_MAX+1],          // Pos X
    mguiEditorStampY[MGUI_EDITOR_STAMP_MAX+1],          // Pos Y
    mguiEditorStampXFactor[MGUI_EDITOR_STAMP_MAX+1],    // Base width (320) multiplier 
    mguiEditorStampYFactor[MGUI_EDITOR_STAMP_MAX+1],    // Base height (240) multiplier
    mguiEditorStampWrap[MGUI_EDITOR_STAMP_MAX+1],       // Wrap (only for text)
    mguiEditorStampAlpha[MGUI_EDITOR_STAMP_MAX+1];      // Opacity (only for non-mouse area)

function int MGUIEditor_GetStampIdFromSlot(int slot) {      return (MGUI_EDITOR_STAMP_DRAWID_END - 1) - (slot<<1); }
function int MGUIEditor_GetSlotFromStampId(int stampId) {   return ((MGUI_EDITOR_STAMP_DRAWID_END - 1) - stampId)>>1; }

function void MGUIEditor_SetStamp(int slot, int type, str content, str font, int x, int y, int xFactor, int yFactor, int wrap, int alpha) {
    mguiEditorStampType[slot] =         type;
    mguiEditorStampContent[slot] =      content;
    mguiEditorStampFont[slot] =         font;
    mguiEditorStampX[slot] =            x;
    mguiEditorStampY[slot] =            y;
    mguiEditorStampXFactor[slot] =      xFactor;
    mguiEditorStampYFactor[slot] =      yFactor;
    mguiEditorStampWrap[slot] =         wrap;
    mguiEditorStampAlpha[slot] =        alpha;

    int hudWidth = MGUIEditor_ToHud(xFactor, MGUI_HUD_WIDTH),
        hudHeight = MGUIEditor_ToHud(yFactor, MGUI_HUD_HEIGHT);

    int stampId = MGUIEditor_GetStampIdFromSlot(slot);
    switch(mguiEditorStampType[slot]) {
        case MGUI_EDITOR_STAMP_GRAPHIC:
            Show(stampId, content, (x*hudWidth)>>16, (y*hudHeight)>>16, hudWidth, hudHeight, alpha);
            break;
        case MGUI_EDITOR_STAMP_TEXT:
            ShowText(stampId, content, font,  (x*hudWidth)>>16, (y*hudHeight)>>16, hudWidth, hudHeight, MGUIEditor_ToHud(wrap, hudWidth), alpha);
            break;
        case MGUI_EDITOR_STAMP_MOUSE_AREA:
            log(s:"todo area");
            break;
    }
    SetMouseArea(stampId, (x*320)>>16, (y*240)>>16, 16, 16, 320, 240);
}

function void MGUIEditor_DeleteStamp(int stampId) {
    for(int slotA = 0; slotA < mguiEditorStampCount; slotA++) {
        if(MGUIEditor_GetStampIdFromSlot(slotA) == stampId) {
            for(int slotB = slotA; slotB < mguiEditorStampCount; slotB++) {
                MGUIEditor_SetStamp(slotB, 
                    mguiEditorStampType[slotB+1], 
                    mguiEditorStampContent[slotB+1], 
                    mguiEditorStampFont[slotB+1],
                    mguiEditorStampX[slotB+1], 
                    mguiEditorStampY[slotB+1], 
                    mguiEditorStampXFactor[slotB+1], 
                    mguiEditorStampYFactor[slotB+1],
                    mguiEditorStampWrap[slotB+1],
                    mguiEditorStampAlpha[slotB+1]
                );
            }

            // Erase the last one
            stampId = MGUIEditor_GetStampIdFromSlot(mguiEditorStampCount-1);
            DeleteMouseArea(stampId);
            Hide(stampId-1);
            mguiEditorStampCount--;
            return;
        }
    }
}

function void MGUIEditor_DrawStampHook(int areaId, int state) {
    int slot = MGUIEditor_GetSlotFromStampId(areaId);
    Show(areaId-1, "MEGAUI_6", 
        (mguiEditorStampX[slot]*320)>>16, (mguiEditorStampY[slot]*240)>>16, 320, 240, state==MGUI_EDITOR_HOOK_FOCUSED ? 1.0 : 0.4);
}