
// -------------------------------------------------------------------------------------------
//     ACS Generator 
// -------------------------------------------------------------------------------------------

// https://cleantextkit.com/remove-timestamps/ (or some other text editor with regex) to remove Zandronum timestamps

script "MegaUI Build" (void) CLIENTSIDE {
    if(!mguiEditorIsRunning) {
        MGUIEditor_Log("You must be in the editor to generate code.");
        MGUIEditor_Play(MGUI_SFX_ERROR);
        terminate;
    }
    int mouseAreaId = 0,
        hudMessageId = 0;
        
    str stringBuilder = "\n
        //===================================//\n
        //          Mega UI ACS [START]      //\n
        //===================================//\n";

    //////////////////////////////
    //     Data parsing         //
    //////////////////////////////

    for(int slot = mguiEditorStampCount-1; slot >= 0; slot--) {

        int hudWidth = MGUIEditor_ToHud(mguiEditorStampXFactor[slot], MGUI_HUD_WIDTH),
            hudHeight = MGUIEditor_ToHud(mguiEditorStampYFactor[slot], MGUI_HUD_HEIGHT),
            x = MGUIEditor_ToHud(mguiEditorStampX[slot], hudWidth),
            y = MGUIEditor_ToHud(mguiEditorStampY[slot], hudHeight);
        str alpha = mguiEditorStampAlpha[slot] == 1.0 ? "1.0" : StrParam(f:mguiEditorStampAlpha[slot]);

        switch(mguiEditorStampType[slot]) {

            // Text stamp
            case MGUI_EDITOR_STAMP_TEXT:
                stringBuilder = StrParam(s:stringBuilder, s:"\nShowText(",
                    s:"50000+", d:hudMessageId, 
                    s:", \"",   s:mguiEditorStampContent[slot], 
                    s:"\", \"", s:mguiEditorStampFont[slot], 
                    s:"\", ",   d:x,
                    s:", ",     d:y,
                    s:", ",     d:hudWidth,
                    s:", ",     d:hudHeight,
                    s:", ",     d:MGUIEditor_ToHud(mguiEditorStampWrap[slot], hudWidth),
                    s:", ",     s:alpha,
                    s:", MGUI_CENTER);"
                );
                hudMessageId++;
                break;

            // Graphic stamp
            case MGUI_EDITOR_STAMP_GRAPHIC:
                stringBuilder = StrParam(s:stringBuilder, s:"\nShow(",
                    s:"50000+", d:hudMessageId, 
                    s:", \"",   s:mguiEditorStampContent[slot], 
                    s:"\", ",   d:x,
                    s:", ",     d:y,
                    s:", ",     d:hudWidth,
                    s:", ",     d:hudHeight,
                    s:", ",     s:alpha,
                    s:");"
                );
                hudMessageId++;
                break;

            // Mouse area stamp
            case MGUI_EDITOR_STAMP_MOUSE_AREA:
                stringBuilder = StrParam(s:stringBuilder, s:"\nSetMouseArea(", d:mouseAreaId,
                    s:", ",     d:x,
                    s:", ",     d:y,
                    s:", ",     d:hudWidth,
                    s:", ",     d:hudHeight,
                    s:", ",     d:mguiEditorStampSizeX[slot],
                    s:", ",     d:mguiEditorStampSizeY[slot],
                    s:");"
                );
                mouseAreaId++;
                break;
        }
    }

    stringBuilder = StrParam(s:stringBuilder, s:"\n\n
        //===================================//\n
        //       	 Mega UI ACS [END]        	//\n
        //===================================//\n");

    Log(s:stringBuilder);
    ConsoleCommand("toggleconsole");
}
